using CcDirector.Core.Tenancy;
using CcDirector.Core.Utilities;
using CcDirector.Gateway.Data;
using CcDirector.Gateway.Data.Entities;
using CcDirector.Gateway.Tenancy;
using Microsoft.EntityFrameworkCore;
using Npgsql;
using Xunit;

namespace CcDirector.Gateway.Tests.Data;

/// <summary>
/// The hosted enrollment gate reads one table - <c>entitlements</c> - and that read is critical enough that
/// its schema qualification is worth pinning explicitly. These facts hold TWO behavior-preserving properties.
///
/// First, the gateway's OWN read path names the <c>gateway</c> schema explicitly on Postgres. On the running
/// model this SELECT is already gateway-qualified via the model-wide HasDefaultSchema, so this is not a fix
/// for any emitted query - it is a GUARD: it proves the qualification is an independent property of this one
/// read and would survive a future change to the model-wide default. It reads the schema from EF's own SQL
/// generation - not from a psql/psycopg2 re-derivation in another client, which does not prove what THIS
/// Gateway emits.
///
/// Second, on SQLite the same read takes NO schema, because SQLite is schemaless. The qualification is a
/// provider CONDITIONAL, not a fallback, so the property is proven on EACH provider's OWN branch - Postgres
/// asserts the schema-qualified SELECT, SQLite asserts the bare one - because a Postgres-branch assertion
/// evaluated on the SQLite model would pass for the wrong reason.
/// </summary>
public sealed class EntitlementSchemaQualificationTests
{
    private const string PgTestConnectionEnvVar = "CC_GATEWAY_TEST_PG_CONNECTION";

    /// <summary>A throwaway but VALID canonical account subject for the query-shape probes. The subject column
    /// is Postgres uuid and the Gateway maps it through a string&lt;-&gt;Guid value converter, so the WHERE
    /// constant must be a real uuid - EF evaluates the converter on it when it generates the SQL literal. The
    /// value is irrelevant to what these facts assert (the FROM clause schema), it only has to parse as a uuid.</summary>
    private const string ProbeSubject = "35543491-85cb-468d-a0c9-560193683105";

    /// <summary>A Fact that skips itself when the throwaway-Postgres connection is unset, so the normal
    /// SQLite test run and CI are unaffected. Anything reading a real PostgresException needs a real server.</summary>
    private sealed class RequiresPostgresFactAttribute : FactAttribute
    {
        public RequiresPostgresFactAttribute()
        {
            if (string.IsNullOrWhiteSpace(Environment.GetEnvironmentVariable(PgTestConnectionEnvVar)))
                Skip = $"Set {PgTestConnectionEnvVar} to a throwaway Postgres connection string to run the real-Postgres proof.";
        }
    }

    /// <summary>Build the model under the Npgsql provider WITHOUT opening a connection. ToQueryString and the
    /// entity's schema annotation come from EF's relational SQL generation for the selected provider, so this
    /// is the Postgres branch's real output - captured from EF itself, the Gateway's own read path.</summary>
    private static GatewayDbContext NpgsqlModel()
    {
        var options = new DbContextOptionsBuilder<GatewayDbContext>()
            .UseNpgsql("Host=localhost;Database=unused;Username=u;Password=p")
            .Options;
        return new GatewayDbContext(options) { ActiveTenant = TenantId.Local.Value };
    }

    private static GatewayDbContext SqliteModel()
    {
        var options = new DbContextOptionsBuilder<GatewayDbContext>()
            .UseSqlite("DataSource=:memory:")
            .Options;
        return new GatewayDbContext(options) { ActiveTenant = TenantId.Local.Value };
    }

    /// <summary>
    /// PROOF (b), Postgres branch. The entitlement read, generated by EF under the Npgsql provider, names the
    /// <c>gateway</c> schema: the SELECT is <c>FROM gateway.entitlements</c> and the entity's schema annotation
    /// is "gateway". This is the branch that ships to the hosted box.
    ///
    /// FAIL-ON-PURPOSE (verified during development): the explicit ToTable schema added here makes this one
    /// read gateway-qualified INDEPENDENTLY of the model-wide default, so removing the model-wide
    /// <c>HasDefaultSchema("gateway")</c> ALONE leaves the FROM clause qualified and this fact green - that is
    /// the independence the guard buys. Removing BOTH the ToTable schema argument in
    /// <see cref="GatewayDbContext"/> AND the model-wide default drops the FROM clause to a bare
    /// <c>entitlements</c> and this assertion reddens.
    /// </summary>
    [Fact]
    public void EntitlementRead_UnderPostgresProvider_GeneratesGatewaySchemaQualifiedSql()
    {
        using var ctx = NpgsqlModel();

        var entity = ctx.Model.FindEntityType(typeof(EntitlementEntity));
        Assert.NotNull(entity);
        Assert.Equal("gateway", entity!.GetSchema());
        Assert.Equal("entitlements", entity.GetTableName());

        var sql = ctx.Entitlements.AsNoTracking().Where(e => e.Subject == ProbeSubject).ToQueryString();

        // The relation is schema-qualified. Postgres quotes an identifier only when it must, so EF emits the
        // bare-but-qualified form gateway.entitlements here; assert on that exact qualified reference.
        Assert.Contains("gateway.entitlements", sql);
        // And it is NOT the bare, schema-less form. The only occurrence of "entitlements" as a FROM target
        // must carry the schema, so there is no bare " entitlements" token sitting where a relation reference
        // goes.
        Assert.DoesNotContain("FROM entitlements", sql);
    }

    /// <summary>
    /// PROOF (b), SQLite branch (the self-host control at the model level). SQLite is schemaless, so the
    /// provider CONDITIONAL must emit NO schema: the entity carries no schema annotation and the SELECT names
    /// the bare table. This is what keeps self-host - which has no schemas - working unchanged, and it is why
    /// the schema argument is gated on the Postgres provider rather than applied unconditionally.
    /// </summary>
    [Fact]
    public void EntitlementRead_UnderSqliteProvider_GeneratesNoSchema()
    {
        using var ctx = SqliteModel();

        var entity = ctx.Model.FindEntityType(typeof(EntitlementEntity));
        Assert.NotNull(entity);
        Assert.Null(entity!.GetSchema());

        var sql = ctx.Entitlements.AsNoTracking().Where(e => e.Subject == ProbeSubject).ToQueryString();
        Assert.DoesNotContain("gateway", sql);
        Assert.Contains("entitlements", sql);
    }

    /// <summary>
    /// PROOF (b), end-to-end on a REAL Postgres server. The gateway-schema-qualified read really resolves the
    /// entitlements table when that table exists in the <c>gateway</c> schema - so the qualification is not
    /// just in the generated string, it hits the right relation. The Gateway migrates the gateway schema but
    /// deliberately does NOT create entitlements (it is excluded from migrations and owned by the payment
    /// side), so the test creates it in the gateway schema exactly as the payment side would, then reads it
    /// through the Gateway's own <see cref="EntitlementRegistry"/>.
    /// </summary>
    [RequiresPostgresFact]
    public void EntitlementRead_AgainstRealPostgres_ResolvesGatewaySchemaTable()
    {
        var conn = Environment.GetEnvironmentVariable(PgTestConnectionEnvVar)!;
        // A CANONICAL D-form uuid subject. The subject column is Postgres uuid and the Gateway reads it through
        // the string<->Guid value converter, so a non-uuid value (the old "sub-live-..." marker) would throw
        // Guid.ParseExact before the read ever reached Postgres. A fresh uuid keeps the fixture rerunnable and
        // unique per run.
        var subject = Guid.NewGuid().ToString("D");
        var subjectGuid = Guid.Parse(subject);
        var previous = Environment.GetEnvironmentVariable(GatewayDatabase.PostgresConnectionEnvVar);
        Environment.SetEnvironmentVariable(GatewayDatabase.PostgresConnectionEnvVar, conn);
        try
        {
            using var db = new GatewayDatabase(new SingleTenantContext());
            using (var ctx = db.CreateUnscopedContext())
            {
                // The payment side owns this table; create it in the gateway schema as that side would - with
                // subject as `uuid`, MATCHING the live column the converter is typed against, so this proves the
                // real scenario (uuid column + the converter's uuid parameter), not a text-column stand-in. Drop
                // first so a stale text-column table from an earlier test build cannot linger and defeat the fix.
                ctx.Database.ExecuteSqlRaw("DROP TABLE IF EXISTS gateway.entitlements;");
                ctx.Database.ExecuteSqlRaw(
                    "CREATE TABLE gateway.entitlements (" +
                    "subject uuid NOT NULL PRIMARY KEY, status text NOT NULL, " +
                    "current_period_end timestamptz NULL, stripe_subscription_id text NULL, " +
                    "updated_at timestamptz NULL, livemode boolean NULL, tier text NULL);");
                // Seed one live, active entitlement on the hosted tier. The subject is bound as a native uuid
                // parameter so it lands in the uuid column exactly as the payment side would write it.
                ctx.Database.ExecuteSqlRaw(
                    "INSERT INTO gateway.entitlements (subject, status, livemode, tier) VALUES ({0}, 'active', true, 'hosted');",
                    subjectGuid);
            }

            var registry = new EntitlementRegistry(db, requireLivemode: true);
            // The full read: the join lands on the uuid column (the 42883 trap is guarded), the outcome is
            // Entitled, and the tier is read back off the same row.
            var decision = registry.Evaluate(subject, DateTime.UtcNow);
            Assert.Equal(EntitlementOutcome.Entitled, decision.Outcome);
            Assert.Equal(EntitlementRegistry.TierHosted, decision.Tier);
        }
        finally
        {
            Environment.SetEnvironmentVariable(GatewayDatabase.PostgresConnectionEnvVar, previous);
        }
    }

    /// <summary>
    /// PROOF (c). When the entitlement read fails with a <see cref="PostgresException"/>, the diagnostic log
    /// carries the two fields that let the server's own error be read - the SQLSTATE code and the server's
    /// message text - and NEVER the account subject. Driven through the Gateway's own read path against a real
    /// server: the Gateway migrates the gateway schema but not the entitlements table (excluded from
    /// migrations), so the read throws SQLSTATE 42P01 (undefined_table) - a genuine PostgresException, not a
    /// constructed one.
    /// </summary>
    [RequiresPostgresFact]
    public void EntitlementReadFailure_OnPostgresException_LogsSqlStateAndMessageText_NeverSubject()
    {
        var conn = Environment.GetEnvironmentVariable(PgTestConnectionEnvVar)!;
        // A CANONICAL D-form uuid subject, unique per run. It MUST be a valid uuid: the converter parses it on
        // the way to Postgres, so a non-uuid marker (the old "sub-PII-marker-...") would throw Guid.ParseExact
        // before the read reached the server, and the intended undefined-table 42P01 would never be produced -
        // the diagnostic path this fact exists to prove would go unexercised. A fresh uuid is still a unique,
        // searchable token, so the never-log-the-subject assertion below is just as unmistakable.
        var subject = Guid.NewGuid().ToString("D");
        var previous = Environment.GetEnvironmentVariable(GatewayDatabase.PostgresConnectionEnvVar);
        Environment.SetEnvironmentVariable(GatewayDatabase.PostgresConnectionEnvVar, conn);

        IReadOnlyList<string> lines;
        EntitlementOutcome outcome;
        try
        {
            using var db = new GatewayDatabase(new SingleTenantContext());

            // Make sure the entitlements table is ABSENT so the gateway-qualified read fails with 42P01.
            using (var ctx = db.CreateUnscopedContext())
                ctx.Database.ExecuteSqlRaw("DROP TABLE IF EXISTS gateway.entitlements;");

            var registry = new EntitlementRegistry(db, requireLivemode: true);

            using var scope = FileLog.RedirectForTests();
            outcome = registry.LookupBySubject(subject, DateTime.UtcNow);
            lines = scope.DrainAndReadLines();
        }
        finally
        {
            Environment.SetEnvironmentVariable(GatewayDatabase.PostgresConnectionEnvVar, previous);
        }

        // Ignorance, not absence: a failed read is Unknown, never a denial or a grant.
        Assert.Equal(EntitlementOutcome.Unknown, outcome);

        var diagnostic = Assert.Single(lines, l => l.Contains("PostgreSQL error"));
        Assert.Contains("SqlState=42P01", diagnostic);
        Assert.Contains("MessageText=", diagnostic);

        // The never-log-the-subject rule holds across EVERY line the read produced, not just the new one.
        Assert.DoesNotContain(lines, l => l.Contains(subject));
    }
}
