using System.Collections.Generic;
using CcDirector.Avalonia;
using Xunit;

namespace CcDirector.Avalonia.Tests;

/// <summary>
/// Tests for the Settings &gt; Agents Add/Edit naming logic (issue #494): auto-name-from-type with
/// "(N)" disambiguation (AC5) and the "don't clobber a customized name" rule (AC9). Pure logic -
/// no Avalonia window is constructed.
/// </summary>
public sealed class AgentEntryNamingTests
{
    // The editor's type labels, mirrored from SettingsDialog.AgentTypeOptions.
    private static readonly string[] AllLabels =
        { "Claude Code", "Codex", "Gemini", "Pi", "OpenCode", "Custom" };

    [Fact]
    public void AutoNameForType_NoExisting_ReturnsBaseLabel()
    {
        var name = AgentEntryNaming.AutoNameForType("Codex", new List<string>());
        Assert.Equal("Codex", name);
    }

    [Fact]
    public void AutoNameForType_NameTaken_AppendsTwo()
    {
        var name = AgentEntryNaming.AutoNameForType("Codex", new[] { "Codex" });
        Assert.Equal("Codex (2)", name);
    }

    [Fact]
    public void AutoNameForType_TwoTaken_AppendsThree()
    {
        var name = AgentEntryNaming.AutoNameForType("Codex", new[] { "Codex", "Codex (2)" });
        Assert.Equal("Codex (3)", name);
    }

    [Fact]
    public void AutoNameForType_UsesLowestFreeIndex_WhenGapExists()
    {
        // "Codex" and "Codex (3)" are taken but "(2)" is free -> fill the gap.
        var name = AgentEntryNaming.AutoNameForType("Codex", new[] { "Codex", "Codex (3)" });
        Assert.Equal("Codex (2)", name);
    }

    [Fact]
    public void AutoNameForType_IsCaseInsensitive()
    {
        var name = AgentEntryNaming.AutoNameForType("Codex", new[] { "codex" });
        Assert.Equal("Codex (2)", name);
    }

    [Fact]
    public void AutoNameForType_IgnoresBlankExistingNames()
    {
        var name = AgentEntryNaming.AutoNameForType("Codex", new[] { "", "   ", "Gemini" });
        Assert.Equal("Codex", name);
    }

    [Fact]
    public void AutoNameForType_MultiWordLabel_Disambiguates()
    {
        var name = AgentEntryNaming.AutoNameForType("Claude Code", new[] { "Claude Code" });
        Assert.Equal("Claude Code (2)", name);
    }

    [Fact]
    public void ShouldAutoFillName_BlankName_ReturnsTrue()
    {
        Assert.True(AgentEntryNaming.ShouldAutoFillName("", AllLabels));
        Assert.True(AgentEntryNaming.ShouldAutoFillName(null, AllLabels));
        Assert.True(AgentEntryNaming.ShouldAutoFillName("   ", AllLabels));
    }

    [Fact]
    public void ShouldAutoFillName_AutoGeneratedBaseLabel_ReturnsTrue()
    {
        // The user picked Codex (name became "Codex") then switches type without editing the name.
        Assert.True(AgentEntryNaming.ShouldAutoFillName("Codex", AllLabels));
    }

    [Fact]
    public void ShouldAutoFillName_AutoGeneratedNumberedVariant_ReturnsTrue()
    {
        Assert.True(AgentEntryNaming.ShouldAutoFillName("Codex (2)", AllLabels));
        Assert.True(AgentEntryNaming.ShouldAutoFillName("Claude Code (3)", AllLabels));
    }

    [Fact]
    public void ShouldAutoFillName_CustomName_ReturnsFalse()
    {
        // AC9: a custom name must not be overwritten by a type change.
        Assert.False(AgentEntryNaming.ShouldAutoFillName("My read-only Codex", AllLabels));
        Assert.False(AgentEntryNaming.ShouldAutoFillName("Codex (my codex)", AllLabels));
    }

    [Fact]
    public void ShouldAutoFillName_NumberedVariantBelowTwo_IsCustom()
    {
        // "Codex (1)" is never auto-generated (auto starts at 2), so treat it as a custom name.
        Assert.False(AgentEntryNaming.ShouldAutoFillName("Codex (1)", AllLabels));
        Assert.False(AgentEntryNaming.ShouldAutoFillName("Codex (0)", AllLabels));
    }
}
