// Typed Gateway client. The TYPES come from the OpenAPI document the Gateway emits
// (src/api/schema.ts, generated by `npm run gen:api`), so the C# DTOs stay the single source
// of truth: a C# DTO change that is not reflected in a regenerated schema fails this build.
//
// The per-machine Gateway token is injected into index.html server-side (window.__GW_TOKEN__)
// and sent as a Bearer header, so the app authenticates whether global Gateway auth is on or
// off (the /sessions endpoint is reachable either way once the bearer is attached).
import type { components } from "./schema";
import type { SessionHistoryDto } from "../history/types";

export type SessionDto = components["schemas"]["SessionDto"];

// Request bodies are typed from the generated OpenAPI schema (the C# DTOs stay the source of
// truth). The buffer/escape/interrupt/transcription responses are not declared in the schema (the
// Gateway returns them via Results.Json without a [Produces] annotation), so they are read with
// narrow local shapes for exactly the fields the mobile views consume.
type PromptRequest = components["schemas"]["PromptRequest"];
type NewSessionRequest = components["schemas"]["NewSessionRequest"];

// One machine (Director) in the fleet, projected from GET /directors. The response is not declared
// in the OpenAPI schema (the Gateway returns it via Results.Json without a [Produces] annotation),
// so it is read with this narrow local shape - the exact subset the add-session flow consumes,
// mirroring the Android phone/CcDirectorClient DirectorInfo.
export interface DirectorInfo {
  directorId: string;
  machineName: string;
  /** Best-effort version label for the picker subtitle. */
  version: string;
  /** When the Gateway last heard from this Director (ISO 8601), or empty. Used to default-select. */
  lastSeen: string;
}

// One recently-used repository on a Director, projected from GET /directors/{id}/repos. Also not in
// the OpenAPI schema; read with this narrow local shape, mirroring the Android RepoInfo.
export interface RepoInfo {
  name: string;
  path: string;
  /** When a session last used this repo (ISO 8601), or empty. The list is sorted newest-used first. */
  lastUsed: string;
}

// The injected token. A value still starting with "__" means the page was served without
// injection (e.g. opened directly from the raw build) - treat that as absent.
function gatewayToken(): string {
  const raw =
    (typeof window !== "undefined" && (window as unknown as { __GW_TOKEN__?: string }).__GW_TOKEN__) || "";
  return raw.indexOf("__") === 0 ? "" : raw;
}

// Exported so the dictation transcription calls (which post raw audio bytes and read a transcript)
// attach the same Bearer the rest of the client uses - the app works with Gateway auth on or off.
export function authHeaders(): HeadersInit {
  const token = gatewayToken();
  return token ? { Authorization: `Bearer ${token}` } : {};
}

// Mirror the per-machine Gateway token into the cc-gateway-token cookie (issue #817). A browser
// WebSocket cannot set an Authorization header, so the live terminal stream
// (GET /sessions/{sid}/stream) authenticates via this cookie, which the same-origin handshake
// carries and the Gateway's AuthMiddleware accepts (HasValidToken checks Bearer OR this cookie).
// The token is already in the page (window.__GW_TOKEN__), so the cookie exposes nothing new; it is
// scoped to this origin. A no-op when the page was served without an injected token (auth is then
// off and the stream needs no credential anyway).
export function ensureGatewayCookie(): void {
  const token = gatewayToken();
  if (!token) return;
  document.cookie = `cc-gateway-token=${encodeURIComponent(token)}; path=/; SameSite=Lax`;
}

export class GatewayError extends Error {
  readonly status: number;
  constructor(status: number, message: string) {
    super(message);
    this.name = "GatewayError";
    this.status = status;
  }
}

// GET /sessions - the fleet roster aggregator. Returns the same SessionDto shape the Cockpit
// Mobile page consumes. Throws GatewayError on a non-2xx so the caller surfaces it (no silent
// fallback). The request is same-origin against the Gateway front door.
export async function listSessions(signal?: AbortSignal): Promise<SessionDto[]> {
  const res = await fetch("/sessions", {
    method: "GET",
    headers: { Accept: "application/json", ...authHeaders() },
    signal,
  });
  if (!res.ok) {
    throw new GatewayError(res.status, `GET /sessions failed: ${res.status}`);
  }
  return (await res.json()) as SessionDto[];
}

// GET /sessions/{sid}/history - the parsed, agent-agnostic conversation history for one session
// (issue #811). The Director's SessionHistoryEndpoint returns SessionHistoryDto; the Gateway
// forwards it verbatim through the catch-all /sessions/{sid}/{**rest} proxy with the injected
// Bearer (no backend change), exactly the way Terminal reaches /prompt. The shape is not declared
// in the OpenAPI schema (it rides the generic per-session proxy), so it is read with the narrow
// local SessionHistoryDto type. A 404 (old Director / unknown session) is surfaced as a
// GatewayError so the caller can treat it as "nothing yet" rather than a hard failure.
export async function getSessionHistory(
  sessionId: string,
  signal?: AbortSignal,
): Promise<SessionHistoryDto> {
  const sid = encodeURIComponent(sessionId);
  const res = await fetch(`/sessions/${sid}/history`, {
    method: "GET",
    headers: { Accept: "application/json", ...authHeaders() },
    signal,
  });
  if (!res.ok) {
    throw new GatewayError(res.status, `GET history failed: ${res.status}`);
  }
  return (await res.json()) as SessionHistoryDto;
}

// Write text (or a raw key escape sequence) to the session's PTY. appendEnter=true submits a typed
// line (the Send button); appendEnter=false writes the bytes verbatim (Enter "\r", arrow keys
// ESC[A/B/C/D) so the session reacts as if the key were pressed at the terminal.
export async function sendPrompt(
  sessionId: string,
  text: string,
  appendEnter: boolean,
  signal?: AbortSignal,
): Promise<void> {
  const sid = encodeURIComponent(sessionId);
  const body: PromptRequest = { text, appendEnter };
  const res = await fetch(`/sessions/${sid}/prompt`, {
    method: "POST",
    headers: { "Content-Type": "application/json", Accept: "application/json", ...authHeaders() },
    body: JSON.stringify(body),
    signal,
  });
  if (!res.ok) {
    throw new GatewayError(res.status, `POST prompt failed: ${res.status}`);
  }
}

// Soft-stop the current turn (the agent driver's Escape). POST /sessions/{sid}/escape.
export async function sendEscape(sessionId: string, signal?: AbortSignal): Promise<void> {
  const sid = encodeURIComponent(sessionId);
  const res = await fetch(`/sessions/${sid}/escape`, {
    method: "POST",
    headers: { Accept: "application/json", ...authHeaders() },
    signal,
  });
  if (!res.ok) {
    throw new GatewayError(res.status, `POST escape failed: ${res.status}`);
  }
}

// Interrupt a running agent turn (Ctrl+C). POST /sessions/{sid}/interrupt.
export async function sendInterrupt(sessionId: string, signal?: AbortSignal): Promise<void> {
  const sid = encodeURIComponent(sessionId);
  const res = await fetch(`/sessions/${sid}/interrupt`, {
    method: "POST",
    headers: { Accept: "application/json", ...authHeaders() },
    signal,
  });
  if (!res.ok) {
    throw new GatewayError(res.status, `POST interrupt failed: ${res.status}`);
  }
}

// ===== Session management (issue #812): the add-session flow + Hold/Resume + Remove =====
// A faithful 1:1 of the Android (MAUI) phone/CcDirectorClient "+ New session" flow and the
// owner's Hold/Remove decision. Every call carries the same Bearer the rest of the client uses, so
// the whole flow works with global Gateway auth on or off.

// GET /directors - the fleet's machines (Directors). Sorted most-recently-seen first so the picker
// can default-select the top one (matching FleetParser.ParseDirectors), tie-broken by machine name.
// Entries with no directorId are dropped (they cannot be addressed). Throws GatewayError on non-2xx
// so the picker shows the real reason instead of a silently empty list.
export async function getDirectors(signal?: AbortSignal): Promise<DirectorInfo[]> {
  const res = await fetch("/directors", {
    method: "GET",
    headers: { Accept: "application/json", ...authHeaders() },
    signal,
  });
  if (!res.ok) {
    throw new GatewayError(res.status, `GET /directors failed: ${res.status}`);
  }
  const raw = (await res.json()) as Array<Record<string, unknown>>;
  const list: DirectorInfo[] = raw
    .map((d) => ({
      directorId: String(d.directorId ?? ""),
      machineName: String(d.machineName ?? ""),
      version: String(d.version ?? ""),
      lastSeen: String(d.lastSeen ?? ""),
    }))
    .filter((d) => d.directorId.length > 0);
  list.sort((a, b) => {
    const bySeen = b.lastSeen.localeCompare(a.lastSeen); // newest-seen first (ISO 8601 sorts lexically)
    if (bySeen !== 0) return bySeen;
    return a.machineName.localeCompare(b.machineName);
  });
  return list;
}

// GET /directors/{id}/repos - a machine's recently-used repositories, sorted newest-used first
// (the server already sorts this way; we re-sort so a mixed body is still correct, matching
// FleetParser.ParseRepos). Entries with no path are dropped. Throws GatewayError on non-2xx.
export async function getRepos(directorId: string, signal?: AbortSignal): Promise<RepoInfo[]> {
  const id = encodeURIComponent(directorId);
  const res = await fetch(`/directors/${id}/repos`, {
    method: "GET",
    headers: { Accept: "application/json", ...authHeaders() },
    signal,
  });
  if (!res.ok) {
    throw new GatewayError(res.status, `GET /directors/${directorId}/repos failed: ${res.status}`);
  }
  const raw = (await res.json()) as Array<Record<string, unknown>>;
  const list: RepoInfo[] = raw
    .map((r) => ({
      name: String(r.name ?? ""),
      path: String(r.path ?? ""),
      lastUsed: String(r.lastUsed ?? ""),
    }))
    .filter((r) => r.path.length > 0);
  list.sort((a, b) => b.lastUsed.localeCompare(a.lastUsed)); // newest-used first
  return list;
}

// POST /directors/{id}/sessions - create a new session in repoPath. Agent is hardcoded "ClaudeCode"
// and wingmanEnabled=false, type omitted, exactly like the Android NewSessionPanel
// (FleetParser.BuildCreateBody). Returns the created SessionDto so the caller can open it. The
// Gateway answers 201 on success; throws GatewayError on non-2xx with the server's reason.
export async function createSession(
  directorId: string,
  repoPath: string,
  signal?: AbortSignal,
): Promise<SessionDto> {
  const id = encodeURIComponent(directorId);
  const body: NewSessionRequest = { repoPath: repoPath.trim(), agent: "ClaudeCode", wingmanEnabled: false };
  const res = await fetch(`/directors/${id}/sessions`, {
    method: "POST",
    headers: { "Content-Type": "application/json", Accept: "application/json", ...authHeaders() },
    body: JSON.stringify(body),
    signal,
  });
  if (!res.ok) {
    let detail = `${res.status}`;
    try {
      const err = (await res.json()) as { detail?: string; error?: string };
      detail = err.detail ?? err.error ?? detail;
    } catch {
      /* non-JSON error body - keep the status code */
    }
    throw new GatewayError(res.status, `Create session failed: ${detail}`);
  }
  return (await res.json()) as SessionDto;
}

// POST /sessions/{sid}/hold - toggle the session's on-hold state. The desired state is sent
// explicitly ({ onHold }) so the call is idempotent; the Director echoes the applied { onHold }.
// Reaches the Director through the Gateway catch-all session proxy with the injected Bearer.
export async function holdSession(
  sessionId: string,
  onHold: boolean,
  signal?: AbortSignal,
): Promise<boolean> {
  const sid = encodeURIComponent(sessionId);
  const res = await fetch(`/sessions/${sid}/hold`, {
    method: "POST",
    headers: { "Content-Type": "application/json", Accept: "application/json", ...authHeaders() },
    body: JSON.stringify({ onHold }),
    signal,
  });
  if (!res.ok) {
    throw new GatewayError(res.status, `POST hold failed: ${res.status}`);
  }
  const result = (await res.json().catch(() => ({}))) as { onHold?: boolean };
  return result.onHold ?? onHold;
}

// DELETE /sessions/{sid} - kill the agent process and remove the session from the roster (the
// Android kill/remove semantics, gated behind a confirmation per the owner's #545 request). Reaches
// the Director through the Gateway catch-all session proxy with the injected Bearer.
export async function killSession(sessionId: string, signal?: AbortSignal): Promise<void> {
  const sid = encodeURIComponent(sessionId);
  const res = await fetch(`/sessions/${sid}`, {
    method: "DELETE",
    headers: { Accept: "application/json", ...authHeaders() },
    signal,
  });
  if (!res.ok) {
    throw new GatewayError(res.status, `DELETE session failed: ${res.status}`);
  }
}

// Dictation transcription (issue #817). Speech-to-text for the Speak dialog goes through the
// EXISTING resilient batch-upload flow the Gateway exposes for the phone (register -> chunk ->
// complete): the same record-then-ship-then-transcribe shape the native mobile app uses, resumable
// on a poor phone network because each landed chunk stays landed. The Gateway transcribes the
// reassembled clip with whatever transcription mode the machine is set to (Local Whisper in
// process, or a remote OpenAI-compatible endpoint) and returns the transcript already run through
// the SAME dictionary-correction engine every surface uses - so we prefer/return that cleaned text.
//
// The Director's own /voice/utterance flow is NOT proxied through the Gateway; this /wingman/
// utterance flow is the Gateway-native equivalent and is reachable by the mobile app same-origin
// with the Bearer, so no backend change is needed.
export async function transcribeUtterance(wav: Blob, signal?: AbortSignal): Promise<string> {
  // 1. Register the upload (mints an id the chunk + complete calls address).
  const reg = await fetch(`/wingman/utterance/upload`, {
    method: "POST",
    headers: { Accept: "application/json", ...authHeaders() },
    signal,
  });
  if (!reg.ok) {
    throw new GatewayError(reg.status, `POST wingman/utterance/upload failed: ${reg.status}`);
  }
  const regBody = (await reg.json()) as { upload_id?: string };
  const uploadId = regBody.upload_id;
  if (!uploadId) {
    throw new GatewayError(reg.status, "transcription register returned no upload id");
  }

  // 2. Upload the whole WAV as chunk 0 (one short utterance per segment). The SHA256 lets the
  //    server reject corruption and treat an identical retry as a free no-op.
  const bytes = new Uint8Array(await wav.arrayBuffer());
  const sha = await sha256Hex(bytes);
  const id = encodeURIComponent(uploadId);
  const put = await fetch(`/wingman/utterance/${id}/chunk/0`, {
    method: "PUT",
    headers: { "Content-Type": "application/octet-stream", "X-Chunk-Sha256": sha, ...authHeaders() },
    body: bytes,
    signal,
  });
  if (!put.ok) {
    throw new GatewayError(put.status, `PUT wingman/utterance chunk failed: ${put.status}`);
  }

  // 3. Complete -> the server reassembles the one chunk, transcribes it, applies the dictionary
  //    correction, and returns the cleaned transcript.
  const comp = await fetch(`/wingman/utterance/${id}/complete`, {
    method: "POST",
    headers: { "Content-Type": "application/json", Accept: "application/json", ...authHeaders() },
    body: JSON.stringify({ totalChunks: 1, mime: "audio/wav", ext: "wav" }),
    signal,
  });
  const compBody = (await comp.json().catch(() => ({}))) as { transcript?: string; error?: string };
  if (!comp.ok) {
    throw new GatewayError(comp.status, compBody.error ?? `transcription failed: ${comp.status}`);
  }
  return (compBody.transcript ?? "").trim();
}

// Hex SHA256 of the upload bytes via the Web Crypto API (available in any secure context, which a
// microphone-capable page already is).
async function sha256Hex(bytes: Uint8Array): Promise<string> {
  const digest = await crypto.subtle.digest("SHA-256", bytes);
  return Array.from(new Uint8Array(digest))
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
}

// ===== Wingman Voice mode (issue #850): the mobile hands-free narration loop =====
// The whole backend is already built and proven on the desktop Cockpit voice tab and the native
// phone app (the explain/voice/ready/menu endpoints below). These typed helpers are the mobile
// PWA's same-origin door to them, each carrying the same Bearer the rest of the client uses so the
// Voice screen works with global Gateway auth on or off. The Wingman is READ-ONLY: explain and the
// voice reads never type into the session; only menu-press / sendPrompt reach the agent, through
// the existing single write chokepoint.
//
// These response shapes are returned by the Gateway via Results.Json WITHOUT a [Produces]
// annotation, so they are not in the generated OpenAPI schema; they are read with narrow local
// types for exactly the fields the Voice screen consumes (the same pattern getDirectors uses).

/** Read-only narration of the latest turn (POST /sessions/{sid}/wingman/explain). Also MARKS the
 *  session as a voice session, so the Gateway's turn-end watcher re-narrates every following turn. */
export interface WingmanExplain {
  reply: string;
  spoken: string;
  replySeconds: number;
  /** True for a fresh/text-only session with nothing to summarize yet (no audio was produced). */
  nothingYet: boolean;
}

/** The precomputed spoken summary + readiness metadata for a session (GET .../wingman/voice). */
export interface WingmanVoice {
  ready: boolean;
  spoken: string;
  reply: string;
  /** ISO-8601 stamp of when this clip was generated; it is the clip's identity (a new turn -> a
   *  new stamp), so the phone uses it to tell a fresh narration from the one it already holds. */
  generatedAt: string;
}

/** One option of a waiting on-screen choice (GET .../wingman/menu). */
export interface WingmanMenuOption {
  /** Short human label, e.g. "1. Yes". */
  key: string;
  /** The exact keystrokes that pick this option. For a single-select menu this includes the
   *  confirm (e.g. "1\r"); for a multiple-select checklist it is just the toggle (e.g. "1"). */
  send: string;
  /** The consequence/risk of choosing this option (<= 18 words). */
  note: string;
  /** True on at most one option - the Wingman's recommended/default pick. */
  recommended: boolean;
}

/** A detected waiting choice and its options (GET .../wingman/menu). */
export interface WingmanMenu {
  isMenu: boolean;
  question: string;
  spoken: string;
  /** "single" to pick exactly one; "multiple" for a pick-any checklist completed by submit. */
  selectionMode: "single" | "multiple";
  /** The keystroke that completes a multiple-select menu (e.g. "\r"); empty for single-select. */
  submit: string;
  options: WingmanMenuOption[];
}

// POST /sessions/{sid}/wingman/explain - mark the session as a voice session AND read its latest
// turn back as a spoken summary, without sending anything into the session. This is what entering
// voice mode fires; the Gateway caches the spoken text + audio so the phone can then download it.
export async function markVoiceAndExplain(sessionId: string, signal?: AbortSignal): Promise<WingmanExplain> {
  const sid = encodeURIComponent(sessionId);
  const res = await fetch(`/sessions/${sid}/wingman/explain`, {
    method: "POST",
    headers: { Accept: "application/json", ...authHeaders() },
    signal,
  });
  if (!res.ok) {
    throw new GatewayError(res.status, `POST wingman/explain failed: ${res.status}`);
  }
  const body = (await res.json()) as Partial<WingmanExplain>;
  return {
    reply: body.reply ?? "",
    spoken: body.spoken ?? "",
    replySeconds: Number(body.replySeconds ?? 0),
    nothingYet: Boolean(body.nothingYet),
  };
}

// GET /sessions/{sid}/wingman/voice - the precomputed spoken summary + readiness for the session's
// current (latest) narration. ready=false means the Gateway has nothing cached yet.
export async function getWingmanVoice(sessionId: string, signal?: AbortSignal): Promise<WingmanVoice> {
  const sid = encodeURIComponent(sessionId);
  const res = await fetch(`/sessions/${sid}/wingman/voice`, {
    method: "GET",
    headers: { Accept: "application/json", ...authHeaders() },
    signal,
  });
  if (!res.ok) {
    throw new GatewayError(res.status, `GET wingman/voice failed: ${res.status}`);
  }
  const body = (await res.json()) as Partial<WingmanVoice>;
  return {
    ready: Boolean(body.ready),
    spoken: body.spoken ?? "",
    reply: body.reply ?? "",
    generatedAt: body.generatedAt ?? "",
  };
}

// GET /sessions/{sid}/wingman/voice/audio - the cached MP3 bytes for the session's current clip.
// Returned as an ArrayBuffer so the phone-side download gate (voice/clips.ts) can store it locally
// and expose a "phone-ready" state distinct from "gateway-ready". Binary, never base64 over the wire.
export async function fetchWingmanVoiceAudio(sessionId: string, signal?: AbortSignal): Promise<ArrayBuffer> {
  const sid = encodeURIComponent(sessionId);
  const res = await fetch(`/sessions/${sid}/wingman/voice/audio`, {
    method: "GET",
    headers: { Accept: "audio/mpeg", ...authHeaders() },
    signal,
  });
  if (!res.ok) {
    throw new GatewayError(res.status, `GET wingman/voice/audio failed: ${res.status}`);
  }
  return res.arrayBuffer();
}

// GET /sessions/{sid}/wingman/menu - is the agent showing an on-screen menu right now, and what are
// its options? The Voice screen reads this to render pressable option buttons. The Gateway returns
// isMenu=false cheaply (no model call) when the terminal does not look like a menu.
export async function getWingmanMenu(sessionId: string, signal?: AbortSignal): Promise<WingmanMenu> {
  const sid = encodeURIComponent(sessionId);
  const res = await fetch(`/sessions/${sid}/wingman/menu`, {
    method: "GET",
    headers: { Accept: "application/json", ...authHeaders() },
    signal,
  });
  if (!res.ok) {
    throw new GatewayError(res.status, `GET wingman/menu failed: ${res.status}`);
  }
  const body = (await res.json()) as Partial<WingmanMenu> & { options?: Partial<WingmanMenuOption>[] };
  return {
    isMenu: Boolean(body.isMenu),
    question: body.question ?? "",
    spoken: body.spoken ?? "",
    selectionMode: body.selectionMode === "multiple" ? "multiple" : "single",
    submit: body.submit ?? "",
    options: (body.options ?? []).map((o) => ({
      key: o.key ?? "",
      send: o.send ?? "",
      note: o.note ?? "",
      recommended: Boolean(o.recommended),
    })),
  };
}

// POST /sessions/{sid}/wingman/menu-press - answer a waiting choice from the phone by sending the
// exact keystrokes. This is the single write chokepoint for a choice (the Wingman charter stays
// read-only). For a single-select menu, `send` is one option's full keystroke and `submit` is
// omitted; for a multiple-select checklist, `send` is the concatenated toggle keystrokes of every
// chosen option and `submit` completes the selection.
export async function pressWingmanMenu(
  sessionId: string,
  send: string,
  submit?: string,
  signal?: AbortSignal,
): Promise<void> {
  const sid = encodeURIComponent(sessionId);
  const body: { send: string; submit?: string } = submit ? { send, submit } : { send };
  const res = await fetch(`/sessions/${sid}/wingman/menu-press`, {
    method: "POST",
    headers: { "Content-Type": "application/json", Accept: "application/json", ...authHeaders() },
    body: JSON.stringify(body),
    signal,
  });
  if (!res.ok) {
    throw new GatewayError(res.status, `POST wingman/menu-press failed: ${res.status}`);
  }
}

// POST /sessions/{sid}/voice-mode { enabled } - the owning Director's authoritative voice flag. This
// is the SAME endpoint the native phone app drives (DirectorVoiceClient.SetVoiceModeAsync): enabled
// sets the session's mobile view mode to Voice, so SessionDto.VoiceMode flips true for every client
// (the roster shows it as a voice session and it persists across navigation); disabled leaves voice
// (view mode -> Text). It reaches the Director through the Gateway catch-all session proxy with the
// injected Bearer, exactly like sendPrompt/holdSession. Switching voice on calls this AND
// markVoiceAndExplain (which marks the Gateway's turn-end re-narration set and reads the first turn).
export async function setVoiceMode(sessionId: string, enabled: boolean, signal?: AbortSignal): Promise<void> {
  const sid = encodeURIComponent(sessionId);
  const res = await fetch(`/sessions/${sid}/voice-mode`, {
    method: "POST",
    headers: { "Content-Type": "application/json", Accept: "application/json", ...authHeaders() },
    body: JSON.stringify({ enabled }),
    signal,
  });
  if (!res.ok) {
    throw new GatewayError(res.status, `POST voice-mode failed: ${res.status}`);
  }
}
