// Typed Gateway client. The TYPES come from the OpenAPI document the Gateway emits
// (src/api/schema.ts, generated by `npm run gen:api`), so the C# DTOs stay the single source
// of truth: a C# DTO change that is not reflected in a regenerated schema fails this build.
//
// The per-machine Gateway token is injected into index.html server-side (window.__GW_TOKEN__)
// and sent as a Bearer header, so the app authenticates whether global Gateway auth is on or
// off (the /sessions endpoint is reachable either way once the bearer is attached).
import type { components } from "./schema";

export type SessionDto = components["schemas"]["SessionDto"];

// The injected token. A value still starting with "__" means the page was served without
// injection (e.g. opened directly from the raw build) - treat that as absent.
function gatewayToken(): string {
  const raw =
    (typeof window !== "undefined" && (window as unknown as { __GW_TOKEN__?: string }).__GW_TOKEN__) || "";
  return raw.indexOf("__") === 0 ? "" : raw;
}

function authHeaders(): HeadersInit {
  const token = gatewayToken();
  return token ? { Authorization: `Bearer ${token}` } : {};
}

export class GatewayError extends Error {
  readonly status: number;
  constructor(status: number, message: string) {
    super(message);
    this.name = "GatewayError";
    this.status = status;
  }
}

// GET /sessions - the fleet roster aggregator. Returns the same SessionDto shape the Cockpit
// Mobile page consumes. Throws GatewayError on a non-2xx so the caller surfaces it (no silent
// fallback). The request is same-origin against the Gateway front door.
export async function listSessions(signal?: AbortSignal): Promise<SessionDto[]> {
  const res = await fetch("/sessions", {
    method: "GET",
    headers: { Accept: "application/json", ...authHeaders() },
    signal,
  });
  if (!res.ok) {
    throw new GatewayError(res.status, `GET /sessions failed: ${res.status}`);
  }
  return (await res.json()) as SessionDto[];
}
