using CcDirector.Core.Tenancy;
using CcDirector.Gateway.Data;
using CcDirector.Gateway.Data.Entities;
using Microsoft.EntityFrameworkCore;
using Xunit;

namespace CcDirector.Gateway.Tests.Data;

/// <summary>
/// The hosted enrollment gate reads one table - <c>entitlements</c> - and that read is critical enough that
/// its schema qualification is worth pinning explicitly. These facts hold TWO behavior-preserving properties.
///
/// First, the gateway's OWN read path names the <c>gateway</c> schema explicitly on Postgres. On the running
/// model this SELECT is already gateway-qualified via the model-wide HasDefaultSchema, so this is not a fix
/// for any emitted query - it is a GUARD: it proves the qualification is an independent property of this one
/// read and would survive a future change to the model-wide default. It reads the schema from EF's own SQL
/// generation - not from a psql/psycopg2 re-derivation in another client, which does not prove what THIS
/// Gateway emits.
///
/// Second, on SQLite the same read takes NO schema, because SQLite is schemaless. The qualification is a
/// provider CONDITIONAL, not a fallback, so the property is proven on EACH provider's OWN branch - Postgres
/// asserts the schema-qualified SELECT, SQLite asserts the bare one - because a Postgres-branch assertion
/// evaluated on the SQLite model would pass for the wrong reason.
///
/// The two halves that need a real PostgreSQL server live in <c>EntitlementSchemaQualificationPostgresTests</c>,
/// in CcDirector.Gateway.DatabaseTests, which only scripts\test-database.ps1 runs against a database.
/// </summary>
public sealed class EntitlementSchemaQualificationTests
{
    /// <summary>A throwaway but VALID canonical account subject for the query-shape probes. The subject column
    /// is Postgres uuid and the Gateway maps it through a string&lt;-&gt;Guid value converter, so the WHERE
    /// constant must be a real uuid - EF evaluates the converter on it when it generates the SQL literal. The
    /// value is irrelevant to what these facts assert (the FROM clause schema), it only has to parse as a uuid.</summary>
    private const string ProbeSubject = "35543491-85cb-468d-a0c9-560193683105";

    /// <summary>Build the model under the Npgsql provider WITHOUT opening a connection. ToQueryString and the
    /// entity's schema annotation come from EF's relational SQL generation for the selected provider, so this
    /// is the Postgres branch's real output - captured from EF itself, the Gateway's own read path.</summary>
    private static GatewayDbContext NpgsqlModel()
    {
        var options = new DbContextOptionsBuilder<GatewayDbContext>()
            .UseNpgsql("Host=localhost;Database=unused;Username=u;Password=p")
            .Options;
        return new GatewayDbContext(options) { ActiveTenant = TenantId.Local.Value };
    }

    private static GatewayDbContext SqliteModel()
    {
        var options = new DbContextOptionsBuilder<GatewayDbContext>()
            .UseSqlite("DataSource=:memory:")
            .Options;
        return new GatewayDbContext(options) { ActiveTenant = TenantId.Local.Value };
    }

    /// <summary>
    /// PROOF (b), Postgres branch. The entitlement read, generated by EF under the Npgsql provider, names the
    /// <c>gateway</c> schema: the SELECT is <c>FROM gateway.entitlements</c> and the entity's schema annotation
    /// is "gateway". This is the branch that ships to the hosted box.
    ///
    /// FAIL-ON-PURPOSE (verified during development): the explicit ToTable schema added here makes this one
    /// read gateway-qualified INDEPENDENTLY of the model-wide default, so removing the model-wide
    /// <c>HasDefaultSchema("gateway")</c> ALONE leaves the FROM clause qualified and this fact green - that is
    /// the independence the guard buys. Removing BOTH the ToTable schema argument in
    /// <see cref="GatewayDbContext"/> AND the model-wide default drops the FROM clause to a bare
    /// <c>entitlements</c> and this assertion reddens.
    /// </summary>
    [Fact]
    public void EntitlementRead_UnderPostgresProvider_GeneratesGatewaySchemaQualifiedSql()
    {
        using var ctx = NpgsqlModel();

        var entity = ctx.Model.FindEntityType(typeof(EntitlementEntity));
        Assert.NotNull(entity);
        Assert.Equal("gateway", entity!.GetSchema());
        Assert.Equal("entitlements", entity.GetTableName());

        var sql = ctx.Entitlements.AsNoTracking().Where(e => e.Subject == ProbeSubject).ToQueryString();

        // The relation is schema-qualified. Postgres quotes an identifier only when it must, so EF emits the
        // bare-but-qualified form gateway.entitlements here; assert on that exact qualified reference.
        Assert.Contains("gateway.entitlements", sql);
        // And it is NOT the bare, schema-less form. The only occurrence of "entitlements" as a FROM target
        // must carry the schema, so there is no bare " entitlements" token sitting where a relation reference
        // goes.
        Assert.DoesNotContain("FROM entitlements", sql);
    }

    /// <summary>
    /// PROOF (b), SQLite branch (the self-host control at the model level). SQLite is schemaless, so the
    /// provider CONDITIONAL must emit NO schema: the entity carries no schema annotation and the SELECT names
    /// the bare table. This is what keeps self-host - which has no schemas - working unchanged, and it is why
    /// the schema argument is gated on the Postgres provider rather than applied unconditionally.
    /// </summary>
    [Fact]
    public void EntitlementRead_UnderSqliteProvider_GeneratesNoSchema()
    {
        using var ctx = SqliteModel();

        var entity = ctx.Model.FindEntityType(typeof(EntitlementEntity));
        Assert.NotNull(entity);
        Assert.Null(entity!.GetSchema());

        var sql = ctx.Entitlements.AsNoTracking().Where(e => e.Subject == ProbeSubject).ToQueryString();
        Assert.DoesNotContain("gateway", sql);
        Assert.Contains("entitlements", sql);
    }
}
