// <auto-generated />
using System;
using System.Collections.Generic;
using CcDirector.Gateway.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CcDirector.Gateway.Migrations.Postgres.Migrations
{
    [DbContext(typeof(GatewayDbContext))]
    partial class GatewayDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("gateway")
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CcDirector.Gateway.Data.Entities.AccountHostedAiSpendEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<long>("AmountMicros")
                        .HasColumnType("bigint");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ObservedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("TransactionCreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "TransactionCreatedUtc");

                    b.HasIndex("TenantId", "Kind", "AmountMicros", "TransactionCreatedUtc");

                    b.ToTable("account_hosted_ai_spend", "gateway");
                });

            modelBuilder.Entity("CcDirector.Gateway.Data.Entities.AccountTrialEntity", b =>
                {
                    b.Property<string>("Subject")
                        .HasColumnType("text")
                        .HasColumnName("subject")
                        .UseCollation("C");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.HasKey("Subject");

                    b.HasIndex("ExpiresAtUtc");

                    b.ToTable("account_trials", "gateway");
                });

            modelBuilder.Entity("CcDirector.Gateway.Data.Entities.ActivityEventEntity", b =>
                {
                    b.Property<string>("TenantId")
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("AfterScreenHash")
                        .HasColumnType("text");

                    b.Property<string>("AgentKind")
                        .HasColumnType("text");

                    b.Property<string>("BeforeScreenHash")
                        .HasColumnType("text");

                    b.Property<string>("BoundedScreenDiff")
                        .HasColumnType("text");

                    b.Property<string>("Cause")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("ContentLength")
                        .HasColumnType("bigint");

                    b.Property<string>("ContentSha256")
                        .HasColumnType("text");

                    b.Property<string>("ContextId")
                        .HasColumnType("text");

                    b.Property<string>("Detail")
                        .HasColumnType("text");

                    b.Property<string>("DetectorMode")
                        .HasColumnType("text");

                    b.Property<string>("DetectorVersion")
                        .HasColumnType("text");

                    b.Property<string>("DirectorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("DirectorSequence")
                        .HasColumnType("bigint");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdentityKind")
                        .HasColumnType("text");

                    b.Property<string>("InputOrigin")
                        .HasColumnType("text");

                    b.Property<string>("Machine")
                        .HasColumnType("text");

                    b.Property<string>("NewState")
                        .HasColumnType("text");

                    b.Property<DateTime>("OccurredUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("OutputByteCount")
                        .HasColumnType("bigint");

                    b.Property<string>("PreviousState")
                        .HasColumnType("text");

                    b.Property<DateTime>("RecordedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Route")
                        .HasColumnType("text");

                    b.Property<string>("SendSource")
                        .HasColumnType("text");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SpokenSpans")
                        .HasColumnType("text");

                    b.Property<string>("TranscriptId")
                        .HasColumnType("text");

                    b.HasKey("TenantId", "EventId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "DirectorId", "DirectorSequence");

                    b.HasIndex("TenantId", "EventType", "OccurredUtc");

                    b.HasIndex("TenantId", "SessionId", "OccurredUtc");

                    b.ToTable("activity_events", "gateway");
                });

            modelBuilder.Entity("CcDirector.Gateway.Data.Entities.CronJobEntity", b =>
                {
                    b.Property<string>("TenantId")
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CronExpression")
                        .HasColumnType("text");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastFiredUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastStatus")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("NextRunUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NotifyOn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NotifyWebhookUrl")
                        .HasColumnType("text");

                    b.Property<bool>("PreventOverlap")
                        .HasColumnType("boolean");

                    b.Property<string>("RunAt")
                        .HasColumnType("text");

                    b.Property<string>("ScheduleKind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TenantId", "Id");

                    b.HasIndex("TenantId");

                    b.ToTable("cron_jobs", "gateway");
                });

            modelBuilder.Entity("CcDirector.Gateway.Data.Entities.CronRunEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FiredUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InfraStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("JobId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Machine")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ScheduledUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint");

                    b.Property<string>("SessionId")
                        .HasColumnType("text");

                    b.Property<string>("TargetDirectorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TaskStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("JobId", "Sequence");

                    b.ToTable("cron_runs", "gateway");
                });

            modelBuilder.Entity("CcDirector.Gateway.Data.Entities.DeviceCredentialEntity", b =>
                {
                    b.Property<string>("DeviceId")
                        .HasColumnType("text")
                        .UseCollation("C");

                    b.Property<string>("AccountSubject")
                        .HasColumnType("text");

                    b.Property<string>("CloudDeviceId")
                        .HasColumnType("text");

                    b.Property<string>("DeviceKeyHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .UseCollation("C");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("IssuedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("KeyLast4")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RevokedReason")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .HasColumnType("text");

                    b.HasKey("DeviceId");

                    b.HasIndex("DeviceKeyHash");

                    b.ToTable("device_credentials", "gateway");
                });

            modelBuilder.Entity("CcDirector.Gateway.Data.Entities.DeviceImportMarkerEntity", b =>
                {
                    b.Property<string>("SourcePath")
                        .HasColumnType("text")
                        .UseCollation("C");

                    b.Property<DateTime>("ImportedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ImportedCount")
                        .HasColumnType("integer");

                    b.HasKey("SourcePath");

                    b.ToTable("device_import_markers", "gateway");
                });

            modelBuilder.Entity("CcDirector.Gateway.Data.Entities.DictationSuggestionDismissalEntity", b =>
                {
                    b.Property<string>("TenantId")
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Term")
                        .HasColumnType("text")
                        .UseCollation("C");

                    b.Property<DateTime>("DismissedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayTerm")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalCount")
                        .HasColumnType("integer");

                    b.Property<string>("VariantsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WrongCount")
                        .HasColumnType("integer");

                    b.HasKey("TenantId", "Term");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "DismissedAtUtc");

                    b.ToTable("dictation_suggestion_dismissals", "gateway");
                });

            modelBuilder.Entity("CcDirector.Gateway.Data.Entities.DictationSuggestionScanEntity", b =>
                {
                    b.Property<string>("TenantId")
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("ScannedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ScreeningError")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ScreeningOk")
                        .HasColumnType("boolean");

                    b.Property<string>("SuggestionsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TenantId");

                    b.HasIndex("TenantId");

                    b.ToTable("dictation_suggestion_scans", "gateway");
                });

            modelBuilder.Entity("CcDirector.Gateway.Data.Entities.DictationSuggestionVerdictEntity", b =>
                {
                    b.Property<string>("TenantId")
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Term")
                        .HasColumnType("text")
                        .UseCollation("C");

                    b.Property<bool>("Approved")
                        .HasColumnType("boolean");

                    b.Property<string>("DisplayTerm")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("JudgedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TenantId", "Term");

                    b.HasIndex("TenantId");

                    b.ToTable("dictation_suggestion_verdicts", "gateway");
                });

            modelBuilder.Entity("CcDirector.Gateway.Data.Entities.DictationTranscriptEntity", b =>
                {
                    b.Property<string>("TenantId")
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CleanedText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("CleanupApplied")
                        .HasColumnType("boolean");

                    b.Property<string>("RawText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TurnId")
                        .HasColumnType("text");

                    b.HasKey("TenantId", "Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "TimestampUtc");

                    b.ToTable("dictation_transcripts", "gateway");
                });

            modelBuilder.Entity("CcDirector.Gateway.Data.Entities.EntitlementEntity", b =>
                {
                    b.Property<Guid>("Subject")
                        .HasColumnType("uuid")
                        .HasColumnName("subject");

                    b.Property<DateTime?>("CurrentPeriodEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("current_period_end");

                    b.Property<bool?>("Livemode")
                        .HasColumnType("boolean")
                        .HasColumnName("livemode");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("StripeSubscriptionId")
                        .HasColumnType("text")
                        .HasColumnName("stripe_subscription_id");

                    b.Property<string>("Tier")
                        .HasColumnType("text")
                        .HasColumnName("tier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Subject");

                    b.ToTable("entitlements", "gateway", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("CcDirector.Gateway.Data.Entities.GovernanceAuditEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Actor")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Detail")
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("OccurredUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("RecordedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RunId")
                        .HasColumnType("uuid");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "Category", "OccurredUtc");

                    b.HasIndex("TenantId", "RunId", "OccurredUtc");

                    b.HasIndex("TenantId", "SessionId", "OccurredUtc");

                    b.ToTable("governance_audit_events", "gateway");
                });

            modelBuilder.Entity("CcDirector.Gateway.Data.Entities.GovernanceEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OccurredUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<DateTime>("RecordedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RunId")
                        .HasColumnType("uuid");

                    b.Property<string>("SessionId")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubjectKind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "OccurredUtc");

                    b.HasIndex("TenantId", "RunId", "OccurredUtc");

                    b.HasIndex("TenantId", "SessionId", "OccurredUtc");

                    b.ToTable("governance_events", "gateway");
                });

            modelBuilder.Entity("CcDirector.Gateway.Data.Entities.KnownRepositoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastUsedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MachineKey")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .UseCollation("C");

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("PathKey")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .UseCollation("C");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "MachineKey", "LastUsedUtc");

                    b.ToTable("known_repositories", "gateway");
                });

            modelBuilder.Entity("CcDirector.Gateway.Data.Entities.MissionNoteEntity", b =>
                {
                    b.Property<string>("TenantId")
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Key")
                        .HasColumnType("text")
                        .UseCollation("C");

                    b.Property<string>("Mission")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Why")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TenantId", "Key");

                    b.HasIndex("TenantId");

                    b.ToTable("mission_notes", "gateway");
                });

            modelBuilder.Entity("CcDirector.Gateway.Data.Entities.PushSubscriptionEntity", b =>
                {
                    b.Property<string>("TenantId")
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Endpoint")
                        .HasColumnType("text")
                        .UseCollation("C");

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("P256dh")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TenantId", "Endpoint");

                    b.HasIndex("TenantId");

                    b.ToTable("push_subscriptions", "gateway");
                });

            modelBuilder.Entity("CcDirector.Gateway.Data.Entities.RepoStateEntity", b =>
                {
                    b.Property<string>("TenantId")
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<string>("DirectorId")
                        .HasColumnType("text");

                    b.Property<string>("RepoPath")
                        .HasColumnType("text");

                    b.Property<string>("BranchesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CollectedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentBranch")
                        .HasColumnType("text");

                    b.Property<string>("DefaultBranch")
                        .HasColumnType("text");

                    b.Property<bool>("IsDirty")
                        .HasColumnType("boolean");

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WorktreesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TenantId", "DirectorId", "RepoPath");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "ReceivedAtUtc");

                    b.ToTable("repo_state", "gateway");
                });

            modelBuilder.Entity("CcDirector.Gateway.Data.Entities.SessionHistoryEntity", b =>
                {
                    b.Property<string>("TenantId")
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<string>("SessionId")
                        .HasColumnType("text")
                        .UseCollation("C");

                    b.Property<string>("AgentKind")
                        .HasColumnType("text");

                    b.Property<long?>("AgentTurnCount")
                        .HasColumnType("bigint");

                    b.Property<string>("BranchesJson")
                        .HasColumnType("text");

                    b.Property<long?>("CacheCreationTokens")
                        .HasColumnType("bigint");

                    b.Property<long?>("CacheReadTokens")
                        .HasColumnType("bigint");

                    b.Property<string>("CommitsJson")
                        .HasColumnType("text");

                    b.Property<double?>("CumulativeIdleSeconds")
                        .HasColumnType("double precision");

                    b.Property<string>("DirectorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DirectorVersion")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EndingKind")
                        .HasColumnType("text");

                    b.Property<string>("EndingLabel")
                        .HasColumnType("text");

                    b.Property<string>("FirstPromptLine")
                        .HasColumnType("text");

                    b.Property<long?>("InputCharacterCount")
                        .HasColumnType("bigint");

                    b.Property<long?>("InputTokens")
                        .HasColumnType("bigint");

                    b.Property<string>("LastActivityState")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastActivityUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastSeenUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LeftUnverifiedJson")
                        .HasColumnType("text");

                    b.Property<string>("MachineName")
                        .HasColumnType("text");

                    b.Property<Guid?>("MissionId")
                        .HasColumnType("uuid");

                    b.Property<string>("MissionName")
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<string>("OriginKind")
                        .HasColumnType("text");

                    b.Property<string>("OriginSurface")
                        .HasColumnType("text");

                    b.Property<long?>("OutputTokens")
                        .HasColumnType("bigint");

                    b.Property<string>("ParentSessionId")
                        .HasColumnType("text");

                    b.Property<long?>("PeakContextTokens")
                        .HasColumnType("bigint");

                    b.Property<string>("PullRequestsJson")
                        .HasColumnType("text");

                    b.Property<string>("RepoName")
                        .HasColumnType("text");

                    b.Property<string>("RepoPath")
                        .HasColumnType("text");

                    b.Property<string>("SessionName")
                        .HasColumnType("text");

                    b.Property<int?>("SessionNumber")
                        .HasColumnType("integer");

                    b.Property<string>("SessionRole")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SummaryAttempts")
                        .HasColumnType("integer");

                    b.Property<bool>("SummaryIsPartial")
                        .HasColumnType("boolean");

                    b.Property<string>("SummaryKind")
                        .HasColumnType("text");

                    b.Property<string>("SummaryText")
                        .HasColumnType("text");

                    b.Property<long?>("TurnCount")
                        .HasColumnType("bigint");

                    b.Property<long?>("WaitingStretchCount")
                        .HasColumnType("bigint");

                    b.Property<string>("WhatWasBuiltJson")
                        .HasColumnType("text");

                    b.HasKey("TenantId", "SessionId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "DirectorId");

                    b.HasIndex("TenantId", "LastSeenUtc");

                    b.ToTable("session_history", "gateway");
                });

            modelBuilder.Entity("CcDirector.Gateway.Data.Entities.SessionHistoryRollupEntity", b =>
                {
                    b.Property<string>("TenantId")
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<string>("RepoKey")
                        .HasColumnType("text")
                        .UseCollation("C");

                    b.Property<DateTime>("DayUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ComputedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InputHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SummaryText")
                        .HasColumnType("text");

                    b.HasKey("TenantId", "RepoKey", "DayUtc");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "DayUtc");

                    b.ToTable("session_history_rollups", "gateway");
                });

            modelBuilder.Entity("CcDirector.Gateway.Data.Entities.SessionKeyEntity", b =>
                {
                    b.Property<string>("TenantId")
                        .HasColumnType("text");

                    b.Property<string>("SessionId")
                        .HasColumnType("text")
                        .UseCollation("C");

                    b.Property<string>("DirectorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("IssuedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .UseCollation("C");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RevokedReason")
                        .HasColumnType("text");

                    b.HasKey("TenantId", "SessionId");

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("KeyHash")
                        .IsUnique();

                    b.ToTable("session_keys", "gateway");
                });

            modelBuilder.Entity("CcDirector.Gateway.Data.Entities.SessionRuleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("CooldownSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DailyCap")
                        .HasColumnType("integer");

                    b.Property<string>("Instruction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PromotedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ScopeAgent")
                        .HasColumnType("text");

                    b.Property<string>("ScopeMachine")
                        .HasColumnType("text");

                    b.Property<string>("ScopeMission")
                        .HasColumnType("text");

                    b.Property<string>("ScopeRepository")
                        .HasColumnType("text");

                    b.Property<string>("ScreenDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.PrimitiveCollection<List<string>>("TriggerWords")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "CreatedUtc");

                    b.ToTable("session_rules", "gateway");
                });

            modelBuilder.Entity("CcDirector.Gateway.Data.Entities.SessionRuleFiringEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Grounding")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("OccurredUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RuleId")
                        .HasColumnType("uuid");

                    b.Property<string>("ScreenText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TypedText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Understanding")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "RuleId", "OccurredUtc");

                    b.HasIndex("TenantId", "SessionId", "OccurredUtc");

                    b.ToTable("session_rule_firings", "gateway");
                });

            modelBuilder.Entity("CcDirector.Gateway.Data.Entities.SessionSpendEntity", b =>
                {
                    b.Property<string>("TenantId")
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<string>("SessionId")
                        .HasColumnType("text")
                        .UseCollation("C");

                    b.Property<string>("AgentKind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BillingMode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("CacheCreationTokens")
                        .HasColumnType("bigint");

                    b.Property<long>("CacheReadTokens")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("FirstObservedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("InputTokens")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastObservedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("MeteredCostMicros")
                        .HasColumnType("bigint");

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<long>("OutputTokens")
                        .HasColumnType("bigint");

                    b.Property<string>("RepoPath")
                        .HasColumnType("text");

                    b.Property<bool>("TokensCaptured")
                        .HasColumnType("boolean");

                    b.HasKey("TenantId", "SessionId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "LastObservedUtc");

                    b.ToTable("session_spend", "gateway");
                });

            modelBuilder.Entity("CcDirector.Gateway.Data.Entities.SessionTurnEntity", b =>
                {
                    b.Property<string>("TenantId")
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<string>("SessionId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .UseCollation("C");

                    b.Property<string>("Generation")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .UseCollation("C");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer");

                    b.Property<string>("ContextId")
                        .HasColumnType("text");

                    b.Property<string>("DirectorId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsMeta")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSidechain")
                        .HasColumnType("boolean");

                    b.Property<string>("PartsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime?>("TimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TenantId", "SessionId", "Generation", "Ordinal");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "ReceivedAtUtc");

                    b.ToTable("session_turns", "gateway");
                });

            modelBuilder.Entity("CcDirector.Gateway.Data.Entities.SessionTurnHeadEntity", b =>
                {
                    b.Property<string>("TenantId")
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<string>("SessionId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .UseCollation("C");

                    b.Property<string>("Agent")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<string>("DirectorId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Generation")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .UseCollation("C");

                    b.Property<string>("GenerationSource")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTime>("GenerationStartedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HistoryState")
                        .HasColumnType("text");

                    b.Property<bool>("IsRawText")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSupported")
                        .HasColumnType("boolean");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TenantId", "SessionId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "DirectorId");

                    b.HasIndex("TenantId", "UpdatedAtUtc");

                    b.ToTable("session_turn_heads", "gateway");
                });

            modelBuilder.Entity("CcDirector.Gateway.Data.Entities.SkillEntity", b =>
                {
                    b.Property<string>("TenantId")
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .UseCollation("C");

                    b.Property<bool>("Archived")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("boolean");

                    b.Property<int>("LatestVersion")
                        .HasColumnType("integer");

                    b.Property<int?>("PublishedVersion")
                        .HasColumnType("integer");

                    b.Property<string>("ShippedContentHash")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TenantId", "Id");

                    b.HasIndex("TenantId");

                    b.ToTable("skills", "gateway");
                });

            modelBuilder.Entity("CcDirector.Gateway.Data.Entities.SkillFileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Encoding")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("utf8");

                    b.Property<bool>("Executable")
                        .HasColumnType("boolean");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("VersionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("VersionId");

                    b.ToTable("skill_files", "gateway");
                });

            modelBuilder.Entity("CcDirector.Gateway.Data.Entities.SkillPlacementStateEntity", b =>
                {
                    b.Property<string>("TenantId")
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<string>("DirectorId")
                        .HasColumnType("text");

                    b.Property<string>("AgentKind")
                        .HasColumnType("text");

                    b.Property<int>("Held")
                        .HasColumnType("integer");

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ObservedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProblemsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Reachable")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("StoreMissing")
                        .HasColumnType("boolean");

                    b.HasKey("TenantId", "DirectorId", "AgentKind");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "ReceivedAtUtc");

                    b.ToTable("skill_placement_state", "gateway");
                });

            modelBuilder.Entity("CcDirector.Gateway.Data.Entities.SkillTenantOverrideEntity", b =>
                {
                    b.Property<string>("TenantId")
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<string>("SkillId")
                        .HasColumnType("text")
                        .UseCollation("C");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TenantId", "SkillId");

                    b.HasIndex("TenantId");

                    b.ToTable("skill_tenant_overrides", "gateway");
                });

            modelBuilder.Entity("CcDirector.Gateway.Data.Entities.SkillVersionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AllowedTools")
                        .HasColumnType("text");

                    b.Property<string>("AuthoredBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BodyMarkdown")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ChangeNote")
                        .HasColumnType("text");

                    b.Property<string>("Compatibility")
                        .HasColumnType("text");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("License")
                        .HasColumnType("text");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("{}");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("PublishedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SkillId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.PrimitiveCollection<List<string>>("Triggers")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "SkillId", "Version")
                        .IsUnique();

                    b.ToTable("skill_versions", "gateway");
                });

            modelBuilder.Entity("CcDirector.Gateway.Data.Entities.SnoozeEntity", b =>
                {
                    b.Property<string>("TenantId")
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<string>("SessionId")
                        .HasColumnType("text")
                        .UseCollation("C");

                    b.Property<string>("DirectorId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("OwnerTurnBaselineUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("PendingMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SnoozeUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TenantId", "SessionId");

                    b.HasIndex("TenantId");

                    b.ToTable("snoozes", "gateway");
                });

            modelBuilder.Entity("CcDirector.Gateway.Data.Entities.TenantEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .UseCollation("C");

                    b.Property<string>("AccountSubject")
                        .IsRequired()
                        .HasColumnType("text")
                        .UseCollation("C");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AccountSubject")
                        .IsUnique();

                    b.ToTable("tenants", "gateway");
                });

            modelBuilder.Entity("CcDirector.Gateway.Data.Entities.TenantSettingEntity", b =>
                {
                    b.Property<string>("TenantId")
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Key")
                        .HasColumnType("text")
                        .UseCollation("C");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TenantId", "Key");

                    b.HasIndex("TenantId");

                    b.ToTable("tenant_settings", "gateway");
                });

            modelBuilder.Entity("CcDirector.Gateway.Data.Entities.TrialExtensionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor");

                    b.Property<string>("MemberEmail")
                        .HasColumnType("text")
                        .HasColumnName("member_email");

                    b.Property<DateTime>("NewExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("new_expires_at_utc");

                    b.Property<DateTime>("PreviousExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("previous_expires_at_utc");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<DateTime>("RecordedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_utc");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject")
                        .UseCollation("C");

                    b.HasKey("Id");

                    b.HasIndex("Subject");

                    b.ToTable("trial_extensions", "gateway");
                });

            modelBuilder.Entity("CcDirector.Gateway.Data.Entities.TurnLogSwitchEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("account")
                        .UseCollation("C");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actor");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("Machine")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("machine")
                        .UseCollation("C");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<DateTime>("RecordedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_utc");

                    b.HasKey("Id");

                    b.HasIndex("Account", "Machine")
                        .IsUnique();

                    b.ToTable("turn_log_switches", "gateway");
                });

            modelBuilder.Entity("CcDirector.Gateway.Data.Entities.WingmanInstructionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AckDefaultContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AckDefaultVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ActiveVersionId")
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("wingman_instructions", "gateway");
                });

            modelBuilder.Entity("CcDirector.Gateway.Data.Entities.WorkListEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Consumer")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("worklists", "gateway");
                });

            modelBuilder.Entity("CcDirector.Gateway.Data.Entities.WorkListItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Area")
                        .HasColumnType("text");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("WorkListId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("WorkListId", "Position");

                    b.ToTable("worklist_items", "gateway");
                });

            modelBuilder.Entity("CcDirector.Gateway.Data.Entities.WorkflowEntity", b =>
                {
                    b.Property<string>("TenantId")
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<bool>("Archived")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("boolean");

                    b.Property<int>("LatestVersion")
                        .HasColumnType("integer");

                    b.Property<int?>("PublishedVersion")
                        .HasColumnType("integer");

                    b.Property<string>("ShippedContentHash")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TenantId", "Id");

                    b.HasIndex("TenantId");

                    b.ToTable("workflows", "gateway");
                });

            modelBuilder.Entity("CcDirector.Gateway.Data.Entities.WorkflowFileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("VersionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("VersionId");

                    b.ToTable("workflow_files", "gateway");
                });

            modelBuilder.Entity("CcDirector.Gateway.Data.Entities.WorkflowRunEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AcceptanceStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AcceptedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("AcceptedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CompletedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("MissionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Outcome")
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("RepoPath")
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<string>("WorkflowId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WorkflowVersion")
                        .HasColumnType("integer");

                    b.Property<Guid>("WorkflowVersionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MissionId");

                    b.HasIndex("TenantId");

                    b.HasIndex("WorkflowId");

                    b.ToTable("workflow_runs", "gateway");
                });

            modelBuilder.Entity("CcDirector.Gateway.Data.Entities.WorkflowTenantOverrideEntity", b =>
                {
                    b.Property<string>("TenantId")
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<string>("WorkflowId")
                        .HasColumnType("text")
                        .UseCollation("C");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TenantId", "WorkflowId");

                    b.HasIndex("TenantId");

                    b.ToTable("workflow_tenant_overrides", "gateway");
                });

            modelBuilder.Entity("CcDirector.Gateway.Data.Entities.WorkflowVersionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AuthoredBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ChangeNote")
                        .HasColumnType("text");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HumanCheckpoint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InstructionsMarkdown")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("PublishedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.Property<string>("WhenToUse")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WorkflowId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "WorkflowId", "Version")
                        .IsUnique();

                    b.ToTable("workflow_versions", "gateway");
                });

            modelBuilder.Entity("CcDirector.Gateway.Data.Entities.WorkspaceEntity", b =>
                {
                    b.Property<string>("TenantId")
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .UseCollation("C");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DirectorId")
                        .HasColumnType("text");

                    b.Property<string>("DirectorName")
                        .HasColumnType("text");

                    b.Property<string>("DocumentJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Machine")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Outcome")
                        .HasColumnType("text");

                    b.Property<int>("SeatCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TenantId", "Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "UpdatedUtc");

                    b.ToTable("workspaces", "gateway");
                });

            modelBuilder.Entity("CcDirector.Gateway.Data.Entities.CronJobEntity", b =>
                {
                    b.OwnsOne("CcDirector.Gateway.Contracts.CronJobAction", "Action", b1 =>
                        {
                            b1.Property<string>("CronJobEntityTenantId")
                                .HasColumnType("text");

                            b1.Property<string>("CronJobEntityId")
                                .HasColumnType("text");

                            b1.Property<bool>("AutoDismiss")
                                .HasColumnType("boolean");

                            b1.Property<string>("RepoPath")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Seed")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("WorkListName")
                                .HasColumnType("text");

                            b1.HasKey("CronJobEntityTenantId", "CronJobEntityId");

                            b1.ToTable("cron_jobs", "gateway");

                            b1.ToJson("Action");

                            b1.WithOwner()
                                .HasForeignKey("CronJobEntityTenantId", "CronJobEntityId");
                        });

                    b.OwnsOne("CcDirector.Gateway.Contracts.CronJobTarget", "Target", b1 =>
                        {
                            b1.Property<string>("CronJobEntityTenantId")
                                .HasColumnType("text");

                            b1.Property<string>("CronJobEntityId")
                                .HasColumnType("text");

                            b1.Property<string>("Machine")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("CronJobEntityTenantId", "CronJobEntityId");

                            b1.ToTable("cron_jobs", "gateway");

                            b1.ToJson("Target");

                            b1.WithOwner()
                                .HasForeignKey("CronJobEntityTenantId", "CronJobEntityId");
                        });

                    b.Navigation("Action")
                        .IsRequired();

                    b.Navigation("Target")
                        .IsRequired();
                });

            modelBuilder.Entity("CcDirector.Gateway.Data.Entities.SessionRuleEntity", b =>
                {
                    b.OwnsMany("CcDirector.Gateway.Rules.RulePrimitiveCall", "Calls", b1 =>
                        {
                            b1.Property<Guid>("SessionRuleEntityId")
                                .HasColumnType("uuid");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("SessionRuleEntityId", "__synthesizedOrdinal");

                            b1.ToTable("session_rules", "gateway");

                            b1.ToJson("Calls");

                            b1.WithOwner()
                                .HasForeignKey("SessionRuleEntityId");

                            b1.OwnsMany("CcDirector.Gateway.Rules.RuleArgument", "Arguments", b2 =>
                                {
                                    b2.Property<Guid>("RulePrimitiveCallSessionRuleEntityId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("RulePrimitiveCall__synthesizedOrdinal")
                                        .HasColumnType("integer");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.Property<string>("Parameter")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Source")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.PrimitiveCollection<List<string>>("Values")
                                        .IsRequired()
                                        .HasColumnType("text[]");

                                    b2.HasKey("RulePrimitiveCallSessionRuleEntityId", "RulePrimitiveCall__synthesizedOrdinal", "__synthesizedOrdinal");

                                    b2.ToTable("session_rules", "gateway");

                                    b2.WithOwner()
                                        .HasForeignKey("RulePrimitiveCallSessionRuleEntityId", "RulePrimitiveCall__synthesizedOrdinal");
                                });

                            b1.Navigation("Arguments");
                        });

                    b.Navigation("Calls");
                });

            modelBuilder.Entity("CcDirector.Gateway.Data.Entities.SessionRuleFiringEntity", b =>
                {
                    b.OwnsMany("CcDirector.Gateway.Data.Entities.RulePrimitiveRunEntity", "PrimitiveRuns", b1 =>
                        {
                            b1.Property<Guid>("SessionRuleFiringEntityId")
                                .HasColumnType("uuid");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<string>("Answer")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Arguments")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("SessionRuleFiringEntityId", "__synthesizedOrdinal");

                            b1.ToTable("session_rule_firings", "gateway");

                            b1.ToJson("PrimitiveRuns");

                            b1.WithOwner()
                                .HasForeignKey("SessionRuleFiringEntityId");
                        });

                    b.Navigation("PrimitiveRuns");
                });

            modelBuilder.Entity("CcDirector.Gateway.Data.Entities.WingmanInstructionEntity", b =>
                {
                    b.OwnsMany("CcDirector.Gateway.Data.Entities.WingmanInstructionVersionOwned", "Versions", b1 =>
                        {
                            b1.Property<Guid>("WingmanInstructionEntityId")
                                .HasColumnType("uuid");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<string>("Content")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTime>("CreatedAtUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Hash")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Id")
                                .HasColumnType("text");

                            b1.Property<string>("Label")
                                .HasColumnType("text");

                            b1.Property<string>("Source")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("WingmanInstructionEntityId", "__synthesizedOrdinal");

                            b1.ToTable("wingman_instructions", "gateway");

                            b1.ToJson("Versions");

                            b1.WithOwner()
                                .HasForeignKey("WingmanInstructionEntityId");
                        });

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("CcDirector.Gateway.Data.Entities.WorkListItemEntity", b =>
                {
                    b.HasOne("CcDirector.Gateway.Data.Entities.WorkListEntity", null)
                        .WithMany("Items")
                        .HasForeignKey("WorkListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CcDirector.Gateway.Data.Entities.WorkflowRunEntity", b =>
                {
                    b.OwnsMany("CcDirector.Gateway.Contracts.WorkflowRunCriterionResultDto", "CriteriaResults", b1 =>
                        {
                            b1.Property<Guid>("WorkflowRunEntityId")
                                .HasColumnType("uuid");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<string>("CriterionId")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTime?>("EvaluatedUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Evaluator")
                                .HasColumnType("text");

                            b1.Property<string>("Note")
                                .HasColumnType("text");

                            b1.Property<string>("ProofUrl")
                                .HasColumnType("text");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("WorkflowRunEntityId", "__synthesizedOrdinal");

                            b1.ToTable("workflow_runs", "gateway");

                            b1.ToJson("CriteriaResults");

                            b1.WithOwner()
                                .HasForeignKey("WorkflowRunEntityId");
                        });

                    b.OwnsMany("CcDirector.Gateway.Contracts.WorkflowRunParticipantDto", "Participants", b1 =>
                        {
                            b1.Property<Guid>("WorkflowRunEntityId")
                                .HasColumnType("uuid");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<string>("AgentKind")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTime>("JoinedUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTime?>("LeftUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Machine")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Role")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("SessionId")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("WorkflowRunEntityId", "__synthesizedOrdinal");

                            b1.ToTable("workflow_runs", "gateway");

                            b1.ToJson("Participants");

                            b1.WithOwner()
                                .HasForeignKey("WorkflowRunEntityId");
                        });

                    b.OwnsMany("CcDirector.Gateway.Contracts.WorkflowRunProofLinkDto", "ProofLinks", b1 =>
                        {
                            b1.Property<Guid>("WorkflowRunEntityId")
                                .HasColumnType("uuid");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<string>("Label")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("WorkflowRunEntityId", "__synthesizedOrdinal");

                            b1.ToTable("workflow_runs", "gateway");

                            b1.ToJson("ProofLinks");

                            b1.WithOwner()
                                .HasForeignKey("WorkflowRunEntityId");
                        });

                    b.Navigation("CriteriaResults");

                    b.Navigation("Participants");

                    b.Navigation("ProofLinks");
                });

            modelBuilder.Entity("CcDirector.Gateway.Data.Entities.WorkflowVersionEntity", b =>
                {
                    b.OwnsMany("CcDirector.Gateway.Contracts.WorkflowOutcomeCriterionDto", "OutcomeCriteria", b1 =>
                        {
                            b1.Property<Guid>("WorkflowVersionEntityId")
                                .HasColumnType("uuid");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<string>("CriterionId")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("ProofHint")
                                .HasColumnType("text");

                            b1.HasKey("WorkflowVersionEntityId", "__synthesizedOrdinal");

                            b1.ToTable("workflow_versions", "gateway");

                            b1.ToJson("OutcomeCriteria");

                            b1.WithOwner()
                                .HasForeignKey("WorkflowVersionEntityId");
                        });

                    b.OwnsMany("CcDirector.Gateway.Contracts.WorkflowStepDto", "Steps", b1 =>
                        {
                            b1.Property<Guid>("WorkflowVersionEntityId")
                                .HasColumnType("uuid");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Doer")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Done")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Reviewer")
                                .HasColumnType("text");

                            b1.HasKey("WorkflowVersionEntityId", "__synthesizedOrdinal");

                            b1.ToTable("workflow_versions", "gateway");

                            b1.ToJson("Steps");

                            b1.WithOwner()
                                .HasForeignKey("WorkflowVersionEntityId");
                        });

                    b.Navigation("OutcomeCriteria");

                    b.Navigation("Steps");
                });

            modelBuilder.Entity("CcDirector.Gateway.Data.Entities.WorkListEntity", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
