import type {
  FactoriesView,
  FactoryActivityView,
  FactoryAgentPage,
  FactoryReportView,
  FactoryWaitingView,
  FactoryWindow,
  FactoryFilters,
  FactoryMapView,
} from "@devthrottle/client-core/factory/factoryAgentsClient";

// Test fixtures in the exact shape the Gateway's FactoryAgentsFold returns. The words are deliberately odd in places
// ("RUNNING-X", "7 asked, waiting for you (fixture)") so a test that finds them proves the page rendered the
// Gateway's words verbatim rather than composing its own.

export const WINDOW: FactoryWindow = {
  key: "last-24h",
  label: "Last 24 hours",
  fromUtc: "2026-09-21T08:00:00Z",
  toUtc: "2026-09-22T08:00:00Z",
  fromLocal: "2026-09-21T08:00",
  toLocal: "2026-09-22T08:00",
  choices: [
    { value: "last-24h", label: "Last 24 hours" },
    { value: "last-7d", label: "Last 7 days" },
    { value: "last-30d", label: "Last 30 days" },
    { value: "custom", label: "Choose dates" },
  ],
};

export const FILTERS: FactoryFilters = {
  factory: "website-business",
  agent: null,
  outcome: null,
  factoryChoices: [
    { value: "", label: "Every factory" },
    { value: "website-business", label: "Website Business" },
  ],
  agentChoices: [
    { value: "", label: "Every factory agent" },
    { value: "front-desk", label: "Front Desk" },
  ],
  outcomeChoices: [
    { value: "", label: "Every outcome" },
    { value: "blocked", label: "Blocked" },
  ],
};

export const FACTORIES: FactoriesView = {
  title: "Factory Agents",
  subtitle: "Virtual employees, and the factories they work in.",
  tabs: [
    { key: "factories", label: "Factories" },
    { key: "agents", label: "All factory agents (2)" },
    { key: "activity", label: "Activity" },
    { key: "reports", label: "Reports" },
  ],
  window: WINDOW,
  factories: [
    {
      id: "website-business",
      title: "Website Business",
      statusWord: "RUNNING-X",
      statusTone: "ok",
      subtitle: "2 factory agents, 1 trigger",
      faultText: null,
      numbers: [
        { text: "7 asked, waiting for you (fixture)", tone: "neutral", target: "waiting", outcome: null, href: "/factory-agents/waiting?factory=website-business" },
        { text: "1 escalated to you", tone: "amber", target: "waiting", outcome: null, href: "/factory-agents/waiting?factory=website-business" },
        { text: "188 empty checks", tone: "grey", target: "activity", outcome: "nothing-to-do", href: "/factory-agents?tab=activity&factory=website-business&outcome=nothing-to-do&window=last-24h" },
      ],
      agents: [
        {
          factoryId: "website-business",
          factoryTitle: "Website Business",
          agentId: "front-desk",
          name: "Front Desk v3",
          wokenBy: "Trigger: New business mail, every 5 min",
          lastRun: "05:32 - 2 asked, 1 escalated",
          statusWord: "IDLE",
          statusTone: "idle",
          href: "/factory-agents/website-business/front-desk",
        },
        {
          factoryId: "website-business",
          factoryTitle: "Website Business",
          agentId: "scout",
          name: "Scout v2",
          wokenBy: "No trigger names it",
          lastRun: "07:00 - 3 asked",
          statusWord: "WORKING",
          statusTone: "working",
          href: "/factory-agents/website-business/scout",
        },
      ],
      pause: {
        action: "pause",
        label: "Pause factory",
        busyLabel: "Pausing...",
        confirm: "Pause the factory Website Business? Its trigger keeps checking.",
      },
      waitingHref: "/factory-agents/waiting?factory=website-business",
      mapHref: "/factory-agents/website-business",
    },
    {
      id: "silent-factory",
      title: "Silent Factory",
      statusWord: "FAULT",
      statusTone: "red",
      subtitle: "1 factory agent, 1 trigger",
      faultText: "No checks ran in the last 24 hours. That is a fault, not a quiet night.",
      numbers: [],
      agents: [],
      pause: { action: "resume", label: "Resume factory", busyLabel: "Resuming...", confirm: null },
      waitingHref: "/factory-agents/waiting?factory=silent-factory",
      mapHref: "/factory-agents/silent-factory",
    },
  ],
  allAgents: [],
  emptyText: null,
};
FACTORIES.allAgents = FACTORIES.factories[0].agents;

export const ACTIVITY: FactoryActivityView = {
  window: WINDOW,
  filters: FILTERS,
  rows: [
    {
      key: "r1",
      time: "02:00",
      factoryTitle: "Website Business",
      who: "Site Keeper v1",
      what: "Started by schedule \"Daily upkeep\"",
      subject: null,
      outcomeWord: "STARTED",
      outcomeTone: "blue",
      collapsed: false,
      sessionId: "131aaaaabbbb",
      sessionLabel: "#131aaaaa",
      link: null,
      note: null,
    },
    {
      key: "r2",
      time: "02:05-04:05",
      factoryTitle: "Website Business",
      who: "Front Desk",
      what: "Checked for new business mail 25 times - nothing to do",
      subject: null,
      outcomeWord: "NOTHING TO DO",
      outcomeTone: "grey",
      collapsed: true,
      sessionId: null,
      sessionLabel: null,
      link: null,
      note: null,
    },
    {
      key: "r3",
      time: "05:30",
      factoryTitle: "Website Business",
      who: "Front Desk v3",
      what: "Asked what it costs after the free build - money question",
      subject: "TN Tree & Crane",
      outcomeWord: "ESCALATED",
      outcomeTone: "amber",
      collapsed: false,
      sessionId: "134",
      sessionLabel: "#134",
      link: null,
      note: "Corrected 22 Sep 08:12: Marked handled by owner (device:abc): money question",
    },
    {
      key: "r4",
      time: "07:22",
      factoryTitle: "Website Business",
      who: "Scout v2",
      what: "Tried to draft to an address on the remove-me list",
      subject: null,
      outcomeWord: "BLOCKED",
      outcomeTone: "red",
      collapsed: false,
      sessionId: "135",
      sessionLabel: "#135",
      link: null,
      note: null,
    },
  ],
  faults: [],
  emptyText: null,
  truncatedText: null,
  footnote: "These rows are permanent. Nothing here can be edited or deleted, by anyone.",
  csvHref: "/gateway/factory-agents/activity.csv?window=last-24h&factory=website-business",
  saveLabel: "Make a report from this",
};

export const ACTIVITY_NO_CHECKS: FactoryActivityView = {
  ...ACTIVITY,
  rows: [],
  faults: ["Silent Factory: No checks ran in the last 24 hours. That is a fault, not a quiet night."],
  emptyText: "Nothing matches these filters in the last 24 hours.",
};

export const AGENT_PAGE: FactoryAgentPage = {
  factoryId: "website-business",
  factoryTitle: "Website Business",
  factoryHref: "/factory-agents/website-business",
  agentId: "front-desk",
  name: "Front Desk v3",
  statusWord: "PAUSED",
  statusTone: "paused",
  definitionText: "Definition not stored yet - #2177 mission 1",
  wokenBy: [
    {
      triggerId: "t1",
      text: "Trigger: New business mail, every 5 min (paused)",
      statusWord: "PAUSED",
      statusTone: "paused",
      statusText: null,
      lastCheck: "22 Sep 07:55 - paused, not started",
    },
  ],
  wokenByEmptyText: null,
  lastCheck: null,
  last7DaysTitle: "Last 7 days",
  last7Days: [
    { text: "14 runs", tone: "neutral", target: null, outcome: null, href: null },
    { text: "3 escalated", tone: "neutral", target: null, outcome: null, href: null },
  ],
  pause: { action: "resume", label: "Resume factory agent", busyLabel: "Resuming...", confirm: null },
  pauseUnavailableText: null,
  askLabel: "Ask the Fleet Manager to change it",
  askHref: "/fleet-manager?ask=Please%20change%20the%20factory%20agent%20Front%20Desk",
  recentTitle: "Recent activity",
  recent: [ACTIVITY.rows[2]],
  recentEmptyText: null,
};

export const WAITING: FactoryWaitingView = {
  factoryId: "website-business",
  title: "Waiting for you - Website Business",
  summary: "2 items: 1 escalated, 1 asked.",
  items: [
    {
      id: "11111111-1111-1111-1111-111111111111",
      word: "ESCALATED",
      tone: "amber",
      factoryTitle: "Website Business",
      subject: "TN Tree & Crane",
      what: "What does it cost after the free build?",
      by: "Front Desk v3, 22 Sep 05:30",
      sessionId: "134",
      sessionLabel: "#134",
      link: "/fixture/mail/thread/1",
      linkLabel: "Open",
      handledLabel: "I have handled it",
      handledBusyLabel: "Marking it handled...",
    },
    {
      id: "22222222-2222-2222-2222-222222222222",
      word: "ASKED",
      tone: "neutral",
      factoryTitle: "Website Business",
      subject: "Brandon's Tree Service",
      what: "Drafted \"Your new hours are live\"",
      by: "Front Desk v3, 22 Sep 04:21",
      sessionId: null,
      sessionLabel: null,
      link: null,
      linkLabel: null,
      handledLabel: null,
      handledBusyLabel: null,
    },
  ],
  emptyText: null,
  truncatedText: null,
};

export const REPORT: FactoryReportView = {
  window: { ...WINDOW, key: "last-7d", label: "Last 7 days" },
  filters: FILTERS,
  tableTitle: "Each factory agent, in the last 7 days",
  columns: ["Factory agent", "Runs", "Done", "Asked", "Escalated", "Blocked", "Sent back", "Failed", "Empty checks"],
  rows: [
    { key: "website-business/front-desk", name: "Front Desk", cells: ["14", "5", "4", "3", "0", "0", "0", "288"] },
    { key: "website-business/scout", name: "Scout", cells: ["7", "7", "7", "0", "3", "0", "0", "0"] },
  ],
  total: { key: "total", name: "Total", cells: ["21", "12", "11", "3", "3", "0", "0", "288"] },
  emptyText: null,
  truncatedText: null,
  faults: [],
  csvHref: "/gateway/factory-agents/activity.csv?window=last-7d",
  saveLabel: "Make a report from this",
  savedTitle: "Saved reports",
  saved: [
    {
      id: "abc123",
      name: "Weekly blocks",
      description: "Website Business, every factory agent, blocked, last 7 days",
      href: "/factory-agents?tab=reports&report=abc123",
      savedText: "Saved 21 Sep 09:00 by owner (device:abc)",
    },
  ],
  savedEmptyText: null,
  openedReportName: null,
};

// The factory page's Map tab (issue #3383): two agents, the owner, a chain and a call, as the Gateway folds them.
export const MAP: FactoryMapView = {
  factoryId: "website-business",
  title: "Website Business",
  emptyText: null,
  sourceText: "Drawn from factory.yaml in cc-consult at 687a1e9. Published 24 Sep 14:02 by session 1234.",
  statusNote: "Each agent's box carries its status and last run, the same as on the factory's card.",
  width: 600,
  height: 300,
  nodes: [
    {
      id: "scout",
      kind: "agent",
      title: "Scout",
      lines: ["daily 07:00"],
      statusWord: "FAULT",
      tone: "red",
      lastRun: "07:00 - 1 failed",
      dashed: false,
      x: 100,
      y: 150,
      width: 100,
      height: 50,
      spec: [
        { label: "Status", text: "FAULT. 07:00 - 1 failed." },
        { label: "Inputs", text: "market: small businesses on Facebook only" },
      ],
      href: "/factory-agents/website-business/scout",
    },
    {
      id: "bookkeeper",
      kind: "agent",
      title: "Bookkeeper",
      lines: ["not built yet"],
      statusWord: null,
      tone: "grey",
      lastRun: null,
      dashed: true,
      x: 300,
      y: 60,
      width: 100,
      height: 50,
      spec: [{ label: "Status", text: "Planned: not built yet." }],
      href: null,
    },
    {
      id: "owner",
      kind: "owner",
      title: "You",
      lines: ["approve, answer"],
      statusWord: null,
      tone: "amber",
      lastRun: null,
      dashed: false,
      x: 480,
      y: 150,
      width: 110,
      height: 44,
      spec: [],
      href: null,
    },
  ],
  edges: [
    {
      from: "scout",
      to: "owner",
      label: "failed: emails you",
      tone: "red",
      line: "solid",
      path: "M 150 150 C 250 150 350 150 415 150",
      head: "425,150 415,153.5 415,146.5",
      labelX: 300,
      labelY: 140,
    },
    {
      from: "scout",
      to: "bookkeeper",
      label: "calls",
      tone: "neutral",
      line: "dashed",
      path: "M 150 140 C 200 100 220 70 245 62",
      head: null,
      labelX: null,
      labelY: null,
    },
  ],
  legend: [
    { text: "On failure, emails you", tone: "red", line: "solid" },
    { text: "Calls another agent inside its run", tone: "neutral", line: "dashed" },
  ],
  changeLabel: "Change this factory with the Fleet Manager",
  changeHref: "/fleet-manager?ask=Please%20change%20the%20factory",
  tabs: [
    { key: "map", label: "Map" },
    { key: "agents", label: "Agents (2)" },
  ],
  agents: FACTORIES.factories[0].agents,
  waitingHref: "/factory-agents/waiting?factory=website-business",
};

export const MAP_EMPTY: FactoryMapView = {
  ...MAP,
  emptyText: "Website Business has not published a map yet.",
  sourceText: null,
  nodes: [],
  edges: [],
};
