import type {
  FactoryActivityView,
  FactoryAgentPage,
  FactoryReportView,
  FactoryWaitingView,
  FactoryWindow,
  FactoryFilters,
} from "@devthrottle/client-core/factory/factoryAgentsClient";
import type {
  FactoriesListView,
  FactoryPageView,
  FactorySeatsView,
} from "@devthrottle/client-core/factory/factoriesScreenClient";

// Test fixtures in the exact shape the Gateway's FactoryAgentsFold returns. The words are deliberately odd in places
// ("RUNNING-X", "7 asked, waiting for you (fixture)") so a test that finds them proves the page rendered the
// Gateway's words verbatim rather than composing its own.

export const WINDOW: FactoryWindow = {
  key: "last-24h",
  label: "Last 24 hours",
  fromUtc: "2026-09-21T08:00:00Z",
  toUtc: "2026-09-22T08:00:00Z",
  fromLocal: "2026-09-21T08:00",
  toLocal: "2026-09-22T08:00",
  choices: [
    { value: "last-24h", label: "Last 24 hours" },
    { value: "last-7d", label: "Last 7 days" },
    { value: "last-30d", label: "Last 30 days" },
    { value: "custom", label: "Choose dates" },
  ],
};

export const FILTERS: FactoryFilters = {
  factory: "website-business",
  agent: null,
  outcome: null,
  factoryChoices: [
    { value: "", label: "Every factory" },
    { value: "website-business", label: "Website Business" },
  ],
  agentChoices: [
    { value: "", label: "Every factory agent" },
    { value: "front-desk", label: "Front Desk" },
  ],
  outcomeChoices: [
    { value: "", label: "Every outcome" },
    { value: "blocked", label: "Blocked" },
  ],
};

export const ACTIVITY: FactoryActivityView = {
  window: WINDOW,
  filters: FILTERS,
  rows: [
    {
      key: "r1",
      time: "02:00",
      factoryTitle: "Website Business",
      who: "Site Keeper v1",
      what: "Started by schedule \"Daily upkeep\"",
      subject: null,
      outcomeWord: "STARTED",
      outcomeTone: "blue",
      collapsed: false,
      sessionId: "131aaaaabbbb",
      sessionLabel: "#131aaaaa",
      link: null,
      note: null,
    },
    {
      key: "r2",
      time: "02:05-04:05",
      factoryTitle: "Website Business",
      who: "Front Desk",
      what: "Checked for new business mail 25 times - nothing to do",
      subject: null,
      outcomeWord: "NOTHING TO DO",
      outcomeTone: "grey",
      collapsed: true,
      sessionId: null,
      sessionLabel: null,
      link: null,
      note: null,
    },
    {
      key: "r3",
      time: "05:30",
      factoryTitle: "Website Business",
      who: "Front Desk v3",
      what: "Asked what it costs after the free build - money question",
      subject: "TN Tree & Crane",
      outcomeWord: "ESCALATED",
      outcomeTone: "amber",
      collapsed: false,
      sessionId: "134",
      sessionLabel: "#134",
      link: null,
      note: "Corrected 22 Sep 08:12: Marked handled by owner (device:abc): money question",
    },
    {
      key: "r4",
      time: "07:22",
      factoryTitle: "Website Business",
      who: "Scout v2",
      what: "Tried to draft to an address on the remove-me list",
      subject: null,
      outcomeWord: "BLOCKED",
      outcomeTone: "red",
      collapsed: false,
      sessionId: "135",
      sessionLabel: "#135",
      link: null,
      note: null,
    },
  ],
  faults: [],
  emptyText: null,
  truncatedText: null,
  footnote: "These rows are permanent. Nothing here can be edited or deleted, by anyone.",
  csvHref: "/gateway/factory-agents/activity.csv?window=last-24h&factory=website-business",
  saveLabel: "Make a report from this",
};

export const ACTIVITY_NO_CHECKS: FactoryActivityView = {
  ...ACTIVITY,
  rows: [],
  faults: ["Silent Factory: No checks ran in the last 24 hours. That is a fault, not a quiet night."],
  emptyText: "Nothing matches these filters in the last 24 hours.",
};

export const AGENT_PAGE: FactoryAgentPage = {
  factoryId: "website-business",
  factoryTitle: "Website Business",
  factoryHref: "/factories/website-business",
  agentId: "front-desk",
  name: "Front Desk v3",
  statusWord: "PAUSED",
  statusTone: "paused",
  definitionText: "Definition not stored yet - #2177 mission 1",
  wokenBy: [
    {
      triggerId: "t1",
      text: "Trigger: New business mail, every 5 min (paused)",
      statusWord: "PAUSED",
      statusTone: "paused",
      statusText: null,
      lastCheck: "22 Sep 07:55 - paused, not started",
    },
  ],
  wokenByEmptyText: null,
  lastCheck: null,
  last7DaysTitle: "Last 7 days",
  last7Days: [
    { text: "14 runs", tone: "neutral", target: null, outcome: null, href: null },
    { text: "3 escalated", tone: "neutral", target: null, outcome: null, href: null },
  ],
  pause: { action: "resume", label: "Resume factory agent", busyLabel: "Resuming...", confirm: null },
  pauseUnavailableText: null,
  askLabel: "Ask the Fleet Manager to change it",
  askHref: "/fleet-manager?ask=Please%20change%20the%20factory%20agent%20Front%20Desk",
  recentTitle: "Recent activity",
  recent: [ACTIVITY.rows[2]],
  recentEmptyText: null,
};

export const WAITING: FactoryWaitingView = {
  factoryId: "website-business",
  title: "Waiting for you - Website Business",
  summary: "2 items: 1 escalated, 1 asked.",
  items: [
    {
      id: "11111111-1111-1111-1111-111111111111",
      word: "ESCALATED",
      tone: "amber",
      factoryTitle: "Website Business",
      subject: "TN Tree & Crane",
      what: "What does it cost after the free build?",
      by: "Front Desk v3, 22 Sep 05:30",
      sessionId: "134",
      sessionLabel: "#134",
      link: "/fixture/mail/thread/1",
      linkLabel: "Open",
      handledLabel: "I have handled it",
      handledBusyLabel: "Marking it handled...",
    },
    {
      id: "22222222-2222-2222-2222-222222222222",
      word: "ASKED",
      tone: "neutral",
      factoryTitle: "Website Business",
      subject: "Brandon's Tree Service",
      what: "Drafted \"Your new hours are live\"",
      by: "Front Desk v3, 22 Sep 04:21",
      sessionId: null,
      sessionLabel: null,
      link: null,
      linkLabel: null,
      handledLabel: null,
      handledBusyLabel: null,
    },
  ],
  emptyText: null,
  truncatedText: null,
};

export const REPORT: FactoryReportView = {
  window: { ...WINDOW, key: "last-7d", label: "Last 7 days" },
  filters: FILTERS,
  tableTitle: "Each factory agent, in the last 7 days",
  columns: ["Factory agent", "Runs", "Done", "Asked", "Escalated", "Blocked", "Sent back", "Failed", "Empty checks"],
  rows: [
    { key: "website-business/front-desk", name: "Front Desk", cells: ["14", "5", "4", "3", "0", "0", "0", "288"] },
    { key: "website-business/scout", name: "Scout", cells: ["7", "7", "7", "0", "3", "0", "0", "0"] },
  ],
  total: { key: "total", name: "Total", cells: ["21", "12", "11", "3", "3", "0", "0", "288"] },
  emptyText: null,
  truncatedText: null,
  faults: [],
  csvHref: "/gateway/factory-agents/activity.csv?window=last-7d",
  saveLabel: "Make a report from this",
  savedTitle: "Saved reports",
  saved: [
    {
      id: "abc123",
      name: "Weekly blocks",
      description: "Website Business, every factory agent, blocked, last 7 days",
      href: "/factories?tab=reports&report=abc123",
      savedText: "Saved 21 Sep 09:00 by owner (device:abc)",
    },
  ],
  savedEmptyText: null,
  openedReportName: null,
};

// The factory page's Map tab (issue #3383): two agents, the owner, a chain and a call, as the Gateway folds them.

// The Factories screen (FactoriesScreenFold), in the exact shape the Gateway returns. Odd words again ("NEEDS YOU-X",
// "1 question (fixture)") so a test that finds them proves the page rendered the Gateway's words verbatim.

export const FACTORY_LIST: FactoriesListView = {
  title: "Factories",
  subtitle: "Each factory runs one business or one job on its own, toward the goal you set for it.",
  tabs: [
    { key: "factories", label: "Factories" },
    { key: "activity", label: "Activity" },
    { key: "reports", label: "Reports" },
  ],
  columns: ["Factory", "Waiting on you", "Status"],
  rows: [
    {
      id: "mindzie-web",
      title: "mindzie Web",
      statusWord: "FAILING",
      statusTone: "red",
      statusReason: "A run of Deployer failed at 06:20.",
      statusLine: "Sender: 4 failures, newest today 12:02 (fixture)",
      statusHref: "/factories/mindzie-web#failing",
      waitingText: "-",
      waitingHref: null,
      href: "/factories/mindzie-web",
      talk: null,
      noCeoText: "No CEO",
    },
    {
      id: "warmforward",
      title: "WarmForward",
      statusWord: "NEEDS YOU-X",
      statusTone: "amber",
      statusReason: "1 question waiting on you.",
      statusLine: "Nora Hale, today 06:20: Is the bunkie meant to be at 20 C? (fixture)",
      statusHref: "/factories/warmforward#waiting",
      waitingText: "1 question (fixture)",
      waitingHref: "/factories/warmforward#waiting",
      href: "/factories/warmforward",
      talk: { label: "Talk to Nora Hale", busyLabel: "Starting the talk with Nora Hale (fixture)...", factoryId: "warmforward", seatId: "nora-hale" },
      noCeoText: null,
    },
    {
      id: "devthrottle",
      title: "DevThrottle",
      statusWord: "RUNNING",
      statusTone: "ok",
      statusReason: "Nothing failed and nothing is waiting on you.",
      statusLine: null,
      statusHref: null,
      waitingText: "-",
      waitingHref: null,
      href: "/factories/devthrottle",
      talk: { label: "Talk to Ada Brennan", busyLabel: "Starting the talk with Ada Brennan (fixture)...", factoryId: "devthrottle", seatId: "ada-brennan" },
      noCeoText: null,
    },
  ],
  footerText: "Worst first: failing, then needs you, then paused, then running.",
  emptyText: null,
  truncatedText: null,
  showArchivedLabel: "Show archived (1) (fixture)",
  hideArchivedLabel: "Hide archived (fixture)",
  archivedRows: [
    {
      id: "tallyhand",
      title: "Tallyhand",
      href: "/factories/tallyhand",
      archivedText: "Archived 6 Oct 23:50 by the owner (fixture)",
      restore: {
        action: "restore",
        factoryId: "tallyhand",
        label: "Restore (fixture)",
        busyLabel: "Restoring Tallyhand (fixture)...",
        confirmTitle: "Restore Tallyhand? (fixture)",
        confirmLines: ["Tallyhand returns to the Factories list. (fixture)", "The archive switched no schedule off, so none is switched on. (fixture)"],
        confirmLabel: "Restore Tallyhand (fixture)",
        danger: false,
        cutoffUtc: null,
        expectedCount: null,
        schedules: [],
      },
    },
  ],
  archivedEmptyText: null,
  outsideTitle: "Schedules outside any factory (fixture)",
  outsideText: "These run on a schedule but are no seat of any factory. (fixture)",
  outsideRows: [
    { id: "cj_job001", name: "Job search", whenText: "Every day at 08:00 (fixture)", machine: "SOREN_NORTH", reason: "In no factory (fixture)" },
    { id: "cj_money1", name: "Money Saver - daily", whenText: "Every day at 06:00 (fixture)", machine: "SOREN_NORTH", reason: "Names the factory 'money-saver', which is not registered (fixture)" },
  ],
  outsideEmptyText: null,
};

export const FACTORY_PAGE: FactoryPageView = {
  id: "warmforward",
  title: "WarmForward",
  crumb: "Factories / WarmForward",
  crumbHref: "/factories",
  statusWord: "NEEDS YOU",
  statusTone: "amber",
  statusReason: "1 question waiting on you.",
  statusLine: "Nora Hale, today 06:20: Is the bunkie meant to be at 20 C? (fixture)",
  statusHref: "/factories/warmforward#waiting",
  ceoText: "CEO Nora Hale",
  seatCountText: "4 seats",
  computerText: "runs on SOREN_NORTH",
  talk: { label: "Talk to Nora Hale", busyLabel: "Starting the talk with Nora Hale (fixture)...", factoryId: "warmforward", seatId: "nora-hale" },
  tabs: [
    { key: "overview", label: "Overview" },
    { key: "seats", label: "Seats (4)" },
    { key: "activity", label: "Activity" },
    { key: "reports", label: "Reports" },
    { key: "memory", label: "Memory" },
    { key: "documents", label: "Documents" },
  ],
  goal: {
    heading: "Goal",
    text: "A cash engine of $15,000-$40,000 a year that runs without your time.",
    note: "Only you change the goal. Approved 4 Oct 2026.",
    emptyText: null,
  },
  goalNumber: {
    heading: "Goal number - posted by Nora Hale, today 06:20",
    valueText: "Propane saved this season: not yet proven",
    asOfText: "As of 6 Oct 2026",
    linkHref: "/fixture/how-it-is-measured",
    linkLabel: "How it is measured",
    emptyText: null,
  },
  failures: {
    heading: "Failing (fixture)",
    note: "A failure stops counting when the same seat later succeeds at the same thing (fixture).",
    items: [
      {
        id: "f1",
        subject: "All Types Fence & Deck",
        what: "keep.page (failed): https://centerconsulting.com/websites/keep/alltypes-fence answers 404 after 20 min",
        by: "Sender, today 12:02",
        sessionId: "171aef53-9bf8-45be-93dd-b9e57f832fc4",
        sessionLabel: "171aef53 (fixture)",
        link: null,
        linkLabel: null,
        handledLabel: "Handled (fixture)",
        handledBusyLabel: "Marking it handled (fixture)...",
        note: null,
      },
      {
        id: null,
        subject: null,
        what: "The schedule for Scout could not start its run today 12:00.",
        by: "Scout's schedule",
        sessionId: null,
        sessionLabel: null,
        link: null,
        linkLabel: null,
        handledLabel: null,
        handledBusyLabel: null,
        note: "This clears when the schedule next starts its run (fixture).",
      },
    ],
  },
  waiting: {
    heading: "Waiting on you",
    items: [
      {
        id: "w1",
        word: "ASKED",
        tone: "amber",
        factoryTitle: "WarmForward",
        subject: "Bunkie",
        what: "Is the Bunkie Bathroom meant to be at 20 C?",
        by: "Nora Hale, today 06:20",
        sessionId: null,
        sessionLabel: null,
        link: null,
        linkLabel: null,
        handledLabel: "I have handled it",
        handledBusyLabel: "Saving...",
      },
    ],
    emptyText: null,
    orderText: "Decisions first, then questions; newest first in each. (fixture)",
    bulkHandled: {
      action: "handled-older",
      factoryId: "warmforward",
      label: "Mark everything older than 7 days as handled (fixture)",
      busyLabel: "Marking 61 items handled (fixture)...",
      confirmTitle: "Mark 61 items handled? (fixture)",
      confirmLines: [
        "This marks 61 items waiting on you from WarmForward as handled: every one from before 29 Sep 23:50, more than 7 days ago. (fixture)",
        "Nothing is deleted. (fixture)",
      ],
      confirmLabel: "Mark 61 handled (fixture)",
      danger: true,
      cutoffUtc: "2026-09-29T23:50:00Z",
      expectedCount: 61,
      schedules: [],
    },
    bulkHandledNote: null,
  },
  ceoLatest: {
    heading: "Latest from the CEO",
    lines: [
      "Today 06:20 - Feed healthy. Found zone 8 holding 20 C; asked you.",
      "Yesterday 06:18 - First run. Constraint: proof.",
    ],
    emptyText: null,
    allLabel: "All reports",
    allHref: "/factories?tab=activity&factory=warmforward&agent=nora-hale",
  },
  lastTalk: { heading: "Last talk with you", text: "None yet." },
  documentsText: "The factory's documents are not on the Gateway yet (fixture).",
  truncatedText: null,
  archive: {
    action: "archive",
    factoryId: "warmforward",
    label: "Archive factory (fixture)",
    busyLabel: "Archiving WarmForward (fixture)...",
    confirmTitle: "Archive WarmForward? (fixture)",
    confirmLines: [
      "WarmForward leaves the Factories list. (fixture)",
      "This Gateway schedule is switched off: \"WarmForward Factory - Nora Hale - morning run\" (cj_a721e6). (fixture)",
      "All its history, its memory and its registry entry are kept. (fixture)",
    ],
    confirmLabel: "Archive WarmForward (fixture)",
    danger: true,
    cutoffUtc: null,
    expectedCount: null,
    schedules: ["cj_a721e6"],
  },
  archivedText: null,
  restore: null,
};

export const FACTORY_SEATS: FactorySeatsView = {
  factoryId: "warmforward",
  title: "WarmForward",
  crumb: "Factories / WarmForward / Seats",
  columns: ["Seat", "When it runs", "Last run", "Computer"],
  rows: [
    {
      seatId: "nora-hale",
      name: "Nora Hale",
      role: "CEO",
      whenText: "Daily 06:15",
      lastRunText: "Today 06:20 - succeeded",
      lastRunTone: "ok",
      computerText: "SOREN_NORTH",
      talk: { label: "Talk", busyLabel: "Starting the talk with nora-hale (fixture)...", factoryId: "warmforward", seatId: "nora-hale" },
    },
    {
      seatId: "value-hunter",
      name: "Value Hunter",
      role: "Value Hunter",
      whenText: "Wednesday 05:30",
      lastRunText: "Not run yet",
      lastRunTone: "grey",
      computerText: "SOREN_NORTH",
      talk: { label: "Talk", busyLabel: "Starting the talk with value-hunter (fixture)...", factoryId: "warmforward", seatId: "value-hunter" },
    },
  ],
  note: "Only seats the CEO hired are listed.",
};
