namespace CcDirector.Gateway.Contracts;

/// <summary>
/// Director -> Gateway request to run the two-way connectivity handshake (issues #223/#224).
/// This request ARRIVING proves leg 1 (Director -> Gateway); the Gateway then proves leg 2
/// by dialing GET {tailnetEndpoint}/verify/{nonce} back on the Director. The nonce is
/// generated fresh by the Director per attempt and correlated on both sides, so neither
/// leg's verdict can be produced by one side alone.
/// </summary>
public sealed class DirectorVerifyRequest
{
    /// <summary>Fresh per-attempt nonce generated by the Director.</summary>
    public string Nonce { get; set; } = "";
}

/// <summary>
/// The Gateway's verdict on one handshake attempt: returned to the asking Director and
/// stamped on the registration (<see cref="DirectorDto.TwoWayVerifiedAt"/>) so the
/// Cockpit and the Director desktop show the same truth.
/// </summary>
public sealed class DirectorVerifyResultDto
{
    /// <summary>
    /// True only when BOTH legs are proven: the verify request arrived (leg 1) AND the
    /// callback to the advertised endpoint answered with the matching Director id (leg 2).
    /// A Director whose heartbeats land but whose endpoint nobody serves gets FALSE here -
    /// the exact SORENLAPTOP failure a naive "connected" light would have missed.
    /// </summary>
    public bool Verified { get; set; }

    /// <summary>The nonce from the request, echoed for correlation.</summary>
    public string Nonce { get; set; } = "";

    /// <summary>Leg 2: did GET {endpoint}/verify/{nonce} answer 2xx as the right Director?</summary>
    public bool CallbackOk { get; set; }

    /// <summary>
    /// Why leg 2 failed (TCP timeout, HTTP status, wrong Director id...). Null when ok.
    /// The asymmetry "you can reach me but I cannot reach you (reason)" IS the diagnosis
    /// and feeds the #223 troubleshooting ladder.
    /// </summary>
    public string? CallbackError { get; set; }

    /// <summary>The URL the Gateway actually dialed for the callback.</summary>
    public string CallbackEndpoint { get; set; } = "";

    /// <summary>Round-trip time of the callback leg in milliseconds.</summary>
    public long CallbackLatencyMs { get; set; }

    /// <summary>
    /// Leg 3 (stream): did a real WebSocket UPGRADE to {endpoint}/verify-ws/{nonce} succeed and
    /// echo the right Director id? This is the path the Cockpit terminal stream uses, so it can
    /// fail even when <see cref="CallbackOk"/> (plain HTTP) passes. False when the leg failed OR
    /// when it was not applicable (old Director without the endpoint - see <see cref="StreamError"/>).
    /// </summary>
    public bool StreamOk { get; set; }

    /// <summary>
    /// Why leg 3 failed, OR a benign note that it was not tested (a Director predating /verify-ws).
    /// Null when the stream leg passed. The Gateway only stamps <see cref="DirectorDto.StreamVerifyError"/>
    /// for a REAL failure, never for "not applicable", so an old Director reads as unknown, not broken.
    /// </summary>
    public string? StreamError { get; set; }

    /// <summary>Round-trip time of the stream (WebSocket upgrade) leg in milliseconds.</summary>
    public long StreamLatencyMs { get; set; }

    /// <summary>Gateway UTC time the verdict was produced.</summary>
    public DateTime VerifiedAt { get; set; }
}

/// <summary>
/// The Director's answer to the Gateway's verify callback (GET /verify/{nonce}).
/// Echoing the Director id lets the Gateway catch an advertised URL that reaches the
/// WRONG process (stale DNS, port collision); the Director records the receipt so it can
/// independently confirm the callback actually landed here and not at an impostor.
/// </summary>
public sealed class VerifyCallbackDto
{
    /// <summary>This Director's id - must match the registration the Gateway dialed.</summary>
    public string DirectorId { get; set; } = "";

    /// <summary>The nonce from the URL, echoed.</summary>
    public string Nonce { get; set; } = "";

    /// <summary>Whether the nonce matched a handshake this Director currently has pending.</summary>
    public bool Known { get; set; }
}
