namespace CcDirector.Gateway.Contracts;

/// <summary>
/// GET/POST /sessions/{sid}/recap response.
///
/// The recap is a markdown text with two sections: "## What was done" and
/// "## What is next". It is generated by a side-claude call (claude --print)
/// against a digest of the session, NOT by prompting the live session itself.
/// Cached per-session in-process; survives until the Director restarts.
/// </summary>
public sealed class RecapResponse
{
    public string SessionId { get; set; } = "";

    /// <summary>The recap text (markdown). Empty when Status != "ok".</summary>
    public string Recap { get; set; } = "";

    /// <summary>UTC timestamp the cached recap was generated.</summary>
    public DateTime? GeneratedAt { get; set; }

    /// <summary>Turn count at the time the recap was generated.</summary>
    public int AtTurnCount { get; set; }

    /// <summary>Current turn count when this response was built.</summary>
    public int CurrentTurnCount { get; set; }

    /// <summary>True when CurrentTurnCount > AtTurnCount (the session has had new
    /// turns since this recap was made; caller may want to POST to regenerate).</summary>
    public bool IsStale { get; set; }

    /// <summary>The cheap model used to generate the recap (e.g. "haiku").</summary>
    public string Model { get; set; } = "";

    /// <summary>Elapsed milliseconds the side-claude call took.</summary>
    public long ElapsedMs { get; set; }

    /// <summary>"ok" | "not_cached" | "no_session_id" | "no_jsonl" | "generation_failed".</summary>
    public string Status { get; set; } = "ok";

    /// <summary>Free-text error message if Status != "ok".</summary>
    public string? Error { get; set; }
}
